export enum ENTITY_NAME {
  // Extra
  USER = 'users',

  // 1.0 Master Data Class - CRUD - 61
  MASTER_PHOTO_LIBRARY = 'master_photo_libraries',
  MASTER_VIDEO_LIBRARY = 'master_video_libraries',
  MASTER_AUDIO_LIBRARY = 'master_audio_libraries',
  MASTER_DIGITAL_LIBRARY = 'master_digital_libraries',
  MASTER_BOOK_LIBRARY = 'master_book_libraries',
  MASTER_WEBSITE_CONTENT = 'master_website_contents',
  MASTER_AI_PROMPT_LIBRARY = 'master_ai_prompt_libraries',
  MASTER_CONTRACT_TEMPLATE = 'master_contract_templates',
  MASTER_EMAIL_SMS_TEMPLATE = 'master_email_sms_templates',
  MASTER_TASK_TEMPLATE = 'master_task_templates',
  MASTER_PROPOSAL_TEMPLATE = 'master_proposal_templates',
  MASTER_TAG_CATEGORY = 'master_tag_categories',
  MASTER_TAG = 'master_tags',
  MASTER_COUNTRY = 'master_countries',
  MASTER_STATE = 'master_states',
  MASTER_COUNTY = 'master_counties',
  MASTER_CITY = 'master_cities',
  MASTER_ZIP_CODE = 'master_zip_codes',
  MASTER_ZONE_TYPE = 'master_zone_types',
  MASTER_CURRENCY = 'master_currencies',
  MASTER_LANGUAGE = 'master_languages',
  MASTER_MEMBERSHIP_TYPE = 'master_membership_types',
  MASTER_DURATION_TYPE = 'master_duration_types',
  MASTER_SUBSCRIPTION_DURATION_TYPE = 'master_subscription_duration_types',
  MASTER_FISCAL_QUARTER = 'master_fiscal_quarters',
  MASTER_COMPANY_TYPE = 'master_company_types',
  MASTER_CONTACT_TYPE = 'master_contact_types',
  MASTER_CONNECT_CHANNEL = 'master_connect_channels',
  MASTER_COURSE_TYPE = 'master_course_types',
  MASTER_COURSE_STATUS = 'master_course_statuses',
  MASTER_COURSE_LEVEL = 'master_course_levels',
  MASTER_COURSE_LESSON_TYPE = 'master_course_lesson_types',
  MASTER_TUTORING_SESSION_STATUS = 'master_tutoring_session_statuses',
  MASTER_STUDENT_COURSE_COMPLETION_STATUS = 'master_student_course_completion_statuses',
  MASTER_EXAM_QUESTION_ANSWER_TYPES = 'master_exam_question_answer_types',
  MASTER_EXAM_DIFFICULTY_LEVEL_TYPE = 'master_exam_difficulty_level_types',
  MASTER_EXAM_GRADE_TYPE = 'master_exam_grade_types',
  MASTER_K12_GRADES = 'master_k12_grades',
  MASTER_INSTITUTE_STATUS = 'master_institute_statuses',
  MASTER_SCHOLARSHIP_APPLICATION_STATUS = 'master_scholarship_application_statuses',
  MASTER_SCHOLARSHIP_TYPE = 'master_scholarship_types',
  MASTER_EMPLOYMENT_STATUS = 'master_employment_statuses',
  MASTER_EMPLOYEE_DEPARTMENT = 'master_employee_departments',
  MASTER_EMPLOYEE_JOB_TITLE = 'master_employee_job_titles',
  MASTER_SALARY_TYPE = 'master_salary_types',
  MASTER_SALARY_PAY_FREQUENCY = 'master_salary_pay_frequencies',
  MASTER_EMPLOYEE_LEAVE_TYPE = 'master_employee_leave_types',
  MASTER_DOCUMENT_TYPE = 'master_document_types',
  MASTER_CONTRACT_TYPE = 'master_contract_types',
  MASTER_CONTRACT_COMMISSION_TYPE = 'master_contract_commission_types',
  MASTER_TASK_STATUS = 'master_task_statuses',
  MASTER_WORK_DAY_TYPE = 'master_work_day_types',
  MASTER_JOB_STATUS = 'master_job_statuses',
  MASTER_JOB_APPLICANT_HIRE_STATUS = 'master_job_applicant_hire_statuses',
  MASTER_STORE_TYPE = 'master_store_types',
  MASTER_ORDER_STATUS_TYPE = 'master_order_status_types',
  MASTER_ORDER_PAYMENT_TYPE = 'master_order_payment_types',
  MASTER_ORDER_CHANNEL_TYPE = 'master_order_channel_types',
  MASTER_LEAD_SOURCE_CHANNEL = 'master_lead_source_channels',
  MASTER_LEAD_STATUS = 'master_lead_statuses',
  MASTER_USER_SIGN_AND_OPT_OUT_LINK = 'master_user_sign_and_opt_out_links',

  // 1.2: App User Role - 6 + 1 --- Mehtab Bhai
  APP_USERS = 'app_users',
  APP_ROLES = 'app_roles',
  APP_USER_ROLES = 'app_user_roles',
  APP_PERMISSIONS = 'app_permissions',
  APP_ROLE_PERMISSIONS = 'app_role_permissions',
  APP_USER_CUSTOM_PERMISSIONS = 'app_user_custom_permissions',
  APP_NOTIFICATIONS = 'app_notifications',
  APP_FEATURES = 'app_features',
  APP_MENU_ITEMS = 'app_menu_items',
  APP_ROLE_MENU_ACCESS = 'app_role_menu_access',

  // 1.3: Zone - 16 --- Shafin Bhai
  ZONES = 'zones', // issue
  ZONE_AREA_BY_ZIPCODES = 'zone_area_by_zipcodes',
  ZONE_ACCOUNT_TEAMS = 'zone_account_teams',
  ZONE_COMPANIES = 'zone_companies',
  ZONE_CONTACTS = 'zone_contacts',
  ZONE_PRODUCT_CATEGORIES = 'zone_product_categories',
  ZONE_PRODUCTS = 'zone_products',
  ZONE_SALES_PROJECTIONS = 'zone_sales_projections',
  ZONE_STORES = 'zone_stores',
  ZONE_STUDENTS = 'zone_students',
  ZONE_INSTITUTES = 'zone_institutes',
  ZONE_TUTORS = 'zone_tutors',
  ZONE_COURSES = 'zone_courses',
  ZONE_COURSE_CATEGORIES = 'zone_course_categories',
  ZONE_JOBS = 'zone_jobs',
  ZONE_SCHOLARSHIPS = 'zone_scholarships',

  // 1.4: Task - 6 --- Shafin Bhai
  TASK_EVENTS = 'task_events',
  TASK_REFERENCES = 'task_references',
  TASK_MEETING_TEAMS = 'task_meeting_teams',
  TASK_DOCUMENTS = 'task_documents',
  TASK_NOTES = 'task_notes',
  TASK_WORK_ITEMS = 'task_work_items',

  // 1.5 Employee - 9 --- Mehtab Bhai
  EMPLOYEES = 'employees',
  EMPLOYEE_TAGS = 'employee_tags',
  EMPLOYEE_WORK_ATTENDANCE_POLICY_ACKNOWLEDGEMENTS = 'employee_work_attendance_policy_acknowledgements',
  EMPLOYEE_WEEKLY_WORK_SCHEDULES = 'employee_weekly_work_schedules',
  EMPLOYEE_ATTENDANCES = 'employee_attendances',
  EMPLOYEE_SALARY_COMPENSATIONS = 'employee_salary_compensations',
  EMPLOYEE_LEAVES = 'employee_leaves',
  EMPLOYEE_TRAININGS = 'employee_trainings',
  EMPLOYEE_PERFORMANCE_REVIEWS = 'employee_performance_reviews',

  // 2.1: CRM Contact Company Groups - 14 --- Mehtab Bhai
  COMPANIES = 'companies',
  COMPANY_TAGS = 'company_tags',
  CONTACTS = 'contacts',
  CONTACT_TAGS = 'contact_tags',
  COMPANY_CONTACT_MAPS = 'company_contact_maps',
  GROUPS = 'groups',
  GROUP_MEMBERS = 'group_members',
  GROUP_MESSAGES = 'group_messages',
  CRM_MESSAGES = 'crm_messages',
  CRM_DOCUMENTS = 'crm_documents',
  CRM_NOTES = 'crm_notes',
  CRM_TEAMS = 'crm_teams',
  CRM_BANK_INFOS = 'crm_bank_infos',
  CRM_REFERRALS = 'crm_referrals',

  // 2.2 Lead Campaign Data Repo - 9 --- Shafin Bhai
  CAMPAIGNS = 'campaigns',
  CAMPAIGN_PROSPECTS = 'campaign_prospects',
  CAMPAIGN_TEAMS = 'campaign_teams',
  SALES_LEADS = 'sales_leads',
  SALES_LEAD_CONTACTS = 'sales_lead_contacts',
  SALES_LEAD_NOTES = 'sales_lead_notes',
  LEAD_SALES_REPS = 'lead_sales_reps',
  LEAD_TASKS_FOLLOWUPS = 'lead_tasks_followups',
  DATA_REPOS = 'data_repos',

  // 2.3 Contract - 4 --- Mehtab Bhai
  CONTRACTS = 'contracts', // issue
  CONTRACT_TERMS = 'contract_terms',
  CONTRACT_MULTIPLE_PARTIES_SIGNS = 'contract_multiple_parties_signs',
  CONTRACT_TASK_REMINDERS = 'contract_task_reminders',

  // 3.1 Store Product Order Discounts - 12 --- Shafin Bhai
  STORES = 'stores',
  PRODUCT_CATEGORIES = 'product_categories',
  PRODUCTS = 'products',
  STORE_PRODUCT_MEDIAS = 'store_product_medias',
  STORE_PRODUCT_TAGS = 'store_product_tags',
  STORE_PRODUCT_TEAMS = 'store_product_teams',
  STORE_PRODUCT_NOTES = 'store_product_notes',
  DISCOUNT_CODES = 'discount_codes',
  SHOPPING_CARTS = 'shopping_carts',
  ORDERS = 'orders',
  ORDER_DETAILS = 'order_details',
  ORDER_PAYMENTS = 'order_payments',

  // 3.2 Job - 6 --- Mehtab Bhai
  JOB_MASTER_CATEGORIES = 'job_master_categories',
  JOBS = 'jobs',
  JOB_TAGS = 'job_tags',
  JOB_APPLICANT_HIRING_BOARDS = 'job_applicant_hiring_boards',
  JOB_HIRING_TEAMS = 'job_hiring_teams',
  JOB_TASK_INTERVIEWS = 'job_task_interviews',

  // 4.1 Courses - 13 --- Shafin Bhai
  COURSE_CATEGORIES = 'course_categories',
  COURSES = 'courses',
  COURSE_SCHEDULES = 'course_schedules',
  COURSE_BUNDLE_COURSES = 'course_bundle_courses',
  COURSE_TAGS = 'course_tags',
  COURSE_MULTIPLE_TUTORS = 'course_multiple_tutors',
  COURSE_MEDIAS = 'course_medias',
  COURSE_MODULES = 'course_modules',
  COURSE_TUTORING_SESSION_COUNTS = 'course_tutoring_session_counts',
  COURSE_LESSONS = 'course_lessons',
  COURSE_LESSON_QUIZS = 'course_lesson_quizs',
  COURSE_ASSIGNMENTS = 'course_assignments',
  COURSE_EXAMS = 'course_exams',

  // 4.2 Student Class Generation - 20 --- Shafin Bhai
  STUDENTS = 'students',
  STUDENT_TAGS = 'student_tags',
  STUDENT_LEARNING_GOALS = 'student_learning_goals',
  STUDENT_GUARDIAN_ACCESSES = 'student_guardian_accesses',
  STUDENTS_COURSE_RECOMMENDATIONS = 'students_course_recommendations',
  STUDENTS_COURSE_ENROLLMENTS = 'students_course_enrollments',
  STUDENT_TUTORING_ENTITLEMENT_AND_USAGES = 'student_tutoring_entitlement_and_usages',
  STUDENT_LEARNING_SCHEDULE_AND_TRACKERS = 'student_learning_schedule_and_trackers',
  STUDENT_TUTORING_SESSIONS = 'student_tutoring_sessions', // issue
  STUDENT_TUTORING_RATING_BY_STUDENTS = 'student_tutoring_rating_by_students',
  STUDENT_TUTORING_RATING_BY_TUTORS = 'student_tutoring_rating_by_tutors',
  STUDENT_TUTORING_RATING_BY_MANAGERS = 'student_tutoring_rating_by_managers',
  STUDENT_QUIZZES = 'student_quizzes',
  STUDENT_QUIZ_RESULTS = 'student_quiz_results',
  STUDENT_COURSE_ASSIGNMENTS = 'student_course_assignments',
  STUDENT_COURSE_ASSIGNMENT_RESULTS = 'student_course_assignment_results',
  STUDENT_EXAMS = 'student_exams',
  STUDENT_EXAM_RESULTS = 'student_exam_results',
  STUDENT_EXAM_DETAILS_COURSE_RECOMMENDATIONS = 'student_exam_details_course_recommendations',
  STUDENT_COURSE_CERTIFICATES = 'student_course_certificates',

  // 4.3 Tutor - 5  --- Mehtab Bhai
  TUTORS = 'tutors',
  TUTOR_TAGS = 'tutor_tags',
  TUTOR_COURSE_EXPERTISE = 'tutor_course_expertise',
  TUTOR_TIME_SLOTS = 'tutor_time_slots',
  TUTOR_STUDENTS = 'tutor_students',

  // 4.4 Institute - 8 --- Mehtab Bhai
  INSTITUTES = 'institutes',
  INSTITUTE_STUDENT_LISTS = 'institute_student_lists',
  INSTITUTE_TUTOR_LISTS = 'institute_tutor_lists',
  INSTITUTE_TAGS = 'institute_tags',
  INSTITUTE_CONTACT_LISTS = 'institute_contact_lists',
  INSTITUTE_SCHOLARSHIP_LISTS = 'institute_scholarship_lists',
  INSTITUTE_COURSES_LISTS = 'institute_courses_lists',
  INSTITUTE_ORDERS_LISTS = 'institute_orders_lists',

  // 4.5 Scholarship - 6 --- Mehtab Bhai
  SCHOLARSHIPS = 'scholarships',
  SCHOLARSHIP_DOCUMENTS = 'scholarship_documents',
  SCHOLARSHIP_INSTITUTE_ZONE_COURSE_MAPS = 'scholarship_institute_zone_course_maps',
  SCHOLARSHIP_STUDENT_APPLICATIONS = 'scholarship_student_applications',
  SCHOLARSHIP_STUDENT_APPLICATION_DOCUMENTS = 'scholarship_student_application_documents',
  SCHOLARSHIP_AWARDS = 'scholarship_awards',

  // 4.6 Exam - 6 --- Mehtab Bhai
  EXAMS = 'exams',
  EXAM_QUESTIONS = 'exam_questions',
  EXAM_QUESTION_DETAILS = 'exam_question_details',
  EXAM_COURSE_MODULE_LESSON_STATS = 'exam_course_module_lesson_stats',
  EXAM_SCHEDULES = 'exam_schedules',
  EXAM_MULTIPLE_AUTHORS = 'exam_multiple_authors',

  // Stripe Related Tables
  STRIPE_PAYMENTS = 'stripe_payments',
  STRIPE_SUBSCRIPTIONS = 'stripe_subscriptions',

  // OTP
  APP_USER_OTPS = 'app_user_otps',
  // New Tables
  MASTER_LEARNING_GOALS = 'master_learning_goals',
}
