export enum Roles {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
}

export enum Status {
  REQUESTED = 'REQUESTED',
  INVITED = 'INVITED',
  JOINED = 'JOINED',
  ACTIVE = 'ACTIVE',
  DRAFT = 'DRAFT',
  CLOSE = 'CLOSE',
}

export enum MediaProvider {
  AWS_S3 = 'AWS_S3',
  Cloudinary = 'Cloudinary',
  LOCAL = 'LOCAL',
  DO_SPACE = 'DO_SPACE',
  GOOGLE_CLOUD = 'GOOGLE_CLOUD',
}

export enum PermissionTitle {
  // user permissions
  USER_CREATE = 'USER:CREATE',
  USER_READ = 'USER:READ',
  USER_UPDATE = 'USER:UPDATE',
  USER_DELETE = 'USER:DELETE',
  USER_COUNT = 'USER:COUNT',

  // master_ai_prompt_library permissions
  MASTER_AI_PROMPT_LIBRARY_CREATE = 'MASTER_AI_PROMPT_LIBRARY:CREATE',
  MASTER_AI_PROMPT_LIBRARY_READ = 'MASTER_AI_PROMPT_LIBRARY:READ',
  MASTER_AI_PROMPT_LIBRARY_UPDATE = 'MASTER_AI_PROMPT_LIBRARY:UPDATE',
  MASTER_AI_PROMPT_LIBRARY_DELETE = 'MASTER_AI_PROMPT_LIBRARY:DELETE',
  MASTER_AI_PROMPT_LIBRARY_COUNT = 'MASTER_AI_PROMPT_LIBRARY:COUNT',

  // master_audio_library permissions
  MASTER_AUDIO_LIBRARY_CREATE = 'MASTER_AUDIO_LIBRARY:CREATE',
  MASTER_AUDIO_LIBRARY_READ = 'MASTER_AUDIO_LIBRARY:READ',
  MASTER_AUDIO_LIBRARY_UPDATE = 'MASTER_AUDIO_LIBRARY:UPDATE',
  MASTER_AUDIO_LIBRARY_DELETE = 'MASTER_AUDIO_LIBRARY:DELETE',
  MASTER_AUDIO_LIBRARY_COUNT = 'MASTER_AUDIO_LIBRARY:COUNT',

  // master_book_library permissions
  MASTER_BOOK_LIBRARY_CREATE = 'MASTER_BOOK_LIBRARY:CREATE',
  MASTER_BOOK_LIBRARY_READ = 'MASTER_BOOK_LIBRARY:READ',
  MASTER_BOOK_LIBRARY_UPDATE = 'MASTER_BOOK_LIBRARY:UPDATE',
  MASTER_BOOK_LIBRARY_DELETE = 'MASTER_BOOK_LIBRARY:DELETE',
  MASTER_BOOK_LIBRARY_COUNT = 'MASTER_BOOK_LIBRARY:COUNT',

  // master_city permissions
  MASTER_CITY_CREATE = 'MASTER_CITY:CREATE',
  MASTER_CITY_READ = 'MASTER_CITY:READ',
  MASTER_CITY_UPDATE = 'MASTER_CITY:UPDATE',
  MASTER_CITY_DELETE = 'MASTER_CITY:DELETE',
  MASTER_CITY_COUNT = 'MASTER_CITY:COUNT',

  // master_company_type permissions
  MASTER_COMPANY_TYPE_CREATE = 'MASTER_COMPANY_TYPE:CREATE',
  MASTER_COMPANY_TYPE_READ = 'MASTER_COMPANY_TYPE:READ',
  MASTER_COMPANY_TYPE_UPDATE = 'MASTER_COMPANY_TYPE:UPDATE',
  MASTER_COMPANY_TYPE_DELETE = 'MASTER_COMPANY_TYPE:DELETE',
  MASTER_COMPANY_TYPE_COUNT = 'MASTER_COMPANY_TYPE:COUNT',

  // master_connect_messaging_channels_type permissions
  MASTER_CONNECT_MESSAGING_CHANNELS_TYPE_CREATE = 'MASTER_CONNECT_MESSAGING_CHANNELS_TYPE:CREATE',
  MASTER_CONNECT_MESSAGING_CHANNELS_TYPE_READ = 'MASTER_CONNECT_MESSAGING_CHANNELS_TYPE:READ',
  MASTER_CONNECT_MESSAGING_CHANNELS_TYPE_UPDATE = 'MASTER_CONNECT_MESSAGING_CHANNELS_TYPE:UPDATE',
  MASTER_CONNECT_MESSAGING_CHANNELS_TYPE_DELETE = 'MASTER_CONNECT_MESSAGING_CHANNELS_TYPE:DELETE',
  MASTER_CONNECT_MESSAGING_CHANNELS_TYPE_COUNT = 'MASTER_CONNECT_MESSAGING_CHANNELS_TYPE:COUNT',

  // master_contact_type permissions
  MASTER_CONTACT_TYPE_CREATE = 'MASTER_CONTACT_TYPE:CREATE',
  MASTER_CONTACT_TYPE_READ = 'MASTER_CONTACT_TYPE:READ',
  MASTER_CONTACT_TYPE_UPDATE = 'MASTER_CONTACT_TYPE:UPDATE',
  MASTER_CONTACT_TYPE_DELETE = 'MASTER_CONTACT_TYPE:DELETE',
  MASTER_CONTACT_TYPE_COUNT = 'MASTER_CONTACT_TYPE:COUNT',

  // master_contract_commission_type permissions
  MASTER_CONTRACT_COMMISSION_TYPE_CREATE = 'MASTER_CONTRACT_COMMISSION_TYPE:CREATE',
  MASTER_CONTRACT_COMMISSION_TYPE_READ = 'MASTER_CONTRACT_COMMISSION_TYPE:READ',
  MASTER_CONTRACT_COMMISSION_TYPE_UPDATE = 'MASTER_CONTRACT_COMMISSION_TYPE:UPDATE',
  MASTER_CONTRACT_COMMISSION_TYPE_DELETE = 'MASTER_CONTRACT_COMMISSION_TYPE:DELETE',
  MASTER_CONTRACT_COMMISSION_TYPE_COUNT = 'MASTER_CONTRACT_COMMISSION_TYPE:COUNT',

  // master_contract_template permissions
  MASTER_CONTRACT_TEMPLATE_CREATE = 'MASTER_CONTRACT_TEMPLATE:CREATE',
  MASTER_CONTRACT_TEMPLATE_READ = 'MASTER_CONTRACT_TEMPLATE:READ',
  MASTER_CONTRACT_TEMPLATE_UPDATE = 'MASTER_CONTRACT_TEMPLATE:UPDATE',
  MASTER_CONTRACT_TEMPLATE_DELETE = 'MASTER_CONTRACT_TEMPLATE:DELETE',
  MASTER_CONTRACT_TEMPLATE_COUNT = 'MASTER_CONTRACT_TEMPLATE:COUNT',

  // master_contract_type permissions
  MASTER_CONTRACT_TYPE_CREATE = 'MASTER_CONTRACT_TYPE:CREATE',
  MASTER_CONTRACT_TYPE_READ = 'MASTER_CONTRACT_TYPE:READ',
  MASTER_CONTRACT_TYPE_UPDATE = 'MASTER_CONTRACT_TYPE:UPDATE',
  MASTER_CONTRACT_TYPE_DELETE = 'MASTER_CONTRACT_TYPE:DELETE',
  MASTER_CONTRACT_TYPE_COUNT = 'MASTER_CONTRACT_TYPE:COUNT',

  // master_county permissions
  MASTER_COUNTY_CREATE = 'MASTER_COUNTY:CREATE',
  MASTER_COUNTY_READ = 'MASTER_COUNTY:READ',
  MASTER_COUNTY_UPDATE = 'MASTER_COUNTY:UPDATE',
  MASTER_COUNTY_DELETE = 'MASTER_COUNTY:DELETE',
  MASTER_COUNTY_COUNT = 'MASTER_COUNTY:COUNT',

  // master_country permissions
  MASTER_COUNTRY_CREATE = 'MASTER_COUNTRY:CREATE',
  MASTER_COUNTRY_READ = 'MASTER_COUNTRY:READ',
  MASTER_COUNTRY_UPDATE = 'MASTER_COUNTRY:UPDATE',
  MASTER_COUNTRY_DELETE = 'MASTER_COUNTRY:DELETE',
  MASTER_COUNTRY_COUNT = 'MASTER_COUNTRY:COUNT',

  // master_course_lesson_type permissions
  MASTER_COURSE_LESSON_TYPE_CREATE = 'MASTER_COURSE_LESSON_TYPE:CREATE',
  MASTER_COURSE_LESSON_TYPE_READ = 'MASTER_COURSE_LESSON_TYPE:READ',
  MASTER_COURSE_LESSON_TYPE_UPDATE = 'MASTER_COURSE_LESSON_TYPE:UPDATE',
  MASTER_COURSE_LESSON_TYPE_DELETE = 'MASTER_COURSE_LESSON_TYPE:DELETE',
  MASTER_COURSE_LESSON_TYPE_COUNT = 'MASTER_COURSE_LESSON_TYPE:COUNT',

  // master_course_level permissions
  MASTER_COURSE_LEVEL_CREATE = 'MASTER_COURSE_LEVEL:CREATE',
  MASTER_COURSE_LEVEL_READ = 'MASTER_COURSE_LEVEL:READ',
  MASTER_COURSE_LEVEL_UPDATE = 'MASTER_COURSE_LEVEL:UPDATE',
  MASTER_COURSE_LEVEL_DELETE = 'MASTER_COURSE_LEVEL:DELETE',
  MASTER_COURSE_LEVEL_COUNT = 'MASTER_COURSE_LEVEL:COUNT',

  // master_course_status permissions
  MASTER_COURSE_STATUS_CREATE = 'MASTER_COURSE_STATUS:CREATE',
  MASTER_COURSE_STATUS_READ = 'MASTER_COURSE_STATUS:READ',
  MASTER_COURSE_STATUS_UPDATE = 'MASTER_COURSE_STATUS:UPDATE',
  MASTER_COURSE_STATUS_DELETE = 'MASTER_COURSE_STATUS:DELETE',
  MASTER_COURSE_STATUS_COUNT = 'MASTER_COURSE_STATUS:COUNT',

  // master_course_type permissions
  MASTER_COURSE_TYPE_CREATE = 'MASTER_COURSE_TYPE:CREATE',
  MASTER_COURSE_TYPE_READ = 'MASTER_COURSE_TYPE:READ',
  MASTER_COURSE_TYPE_UPDATE = 'MASTER_COURSE_TYPE:UPDATE',
  MASTER_COURSE_TYPE_DELETE = 'MASTER_COURSE_TYPE:DELETE',
  MASTER_COURSE_TYPE_COUNT = 'MASTER_COURSE_TYPE:COUNT',

  // master_currency permissions
  MASTER_CURRENCY_CREATE = 'MASTER_CURRENCY:CREATE',
  MASTER_CURRENCY_READ = 'MASTER_CURRENCY:READ',
  MASTER_CURRENCY_UPDATE = 'MASTER_CURRENCY:UPDATE',
  MASTER_CURRENCY_DELETE = 'MASTER_CURRENCY:DELETE',
  MASTER_CURRENCY_COUNT = 'MASTER_CURRENCY:COUNT',

  // master_digital_library permissions
  MASTER_DIGITAL_LIBRARY_CREATE = 'MASTER_DIGITAL_LIBRARY:CREATE',
  MASTER_DIGITAL_LIBRARY_READ = 'MASTER_DIGITAL_LIBRARY:READ',
  MASTER_DIGITAL_LIBRARY_UPDATE = 'MASTER_DIGITAL_LIBRARY:UPDATE',
  MASTER_DIGITAL_LIBRARY_DELETE = 'MASTER_DIGITAL_LIBRARY:DELETE',
  MASTER_DIGITAL_LIBRARY_COUNT = 'MASTER_DIGITAL_LIBRARY:COUNT',

  // master_document_type permissions
  MASTER_DOCUMENT_TYPE_CREATE = 'MASTER_DOCUMENT_TYPE:CREATE',
  MASTER_DOCUMENT_TYPE_READ = 'MASTER_DOCUMENT_TYPE:READ',
  MASTER_DOCUMENT_TYPE_UPDATE = 'MASTER_DOCUMENT_TYPE:UPDATE',
  MASTER_DOCUMENT_TYPE_DELETE = 'MASTER_DOCUMENT_TYPE:DELETE',
  MASTER_DOCUMENT_TYPE_COUNT = 'MASTER_DOCUMENT_TYPE:COUNT',

  // master_duration_type permissions
  MASTER_DURATION_TYPE_CREATE = 'MASTER_DURATION_TYPE:CREATE',
  MASTER_DURATION_TYPE_READ = 'MASTER_DURATION_TYPE:READ',
  MASTER_DURATION_TYPE_UPDATE = 'MASTER_DURATION_TYPE:UPDATE',
  MASTER_DURATION_TYPE_DELETE = 'MASTER_DURATION_TYPE:DELETE',
  MASTER_DURATION_TYPE_COUNT = 'MASTER_DURATION_TYPE:COUNT',

  // master_email_sms_template permissions
  MASTER_EMAIL_SMS_TEMPLATE_CREATE = 'MASTER_EMAIL_SMS_TEMPLATE:CREATE',
  MASTER_EMAIL_SMS_TEMPLATE_READ = 'MASTER_EMAIL_SMS_TEMPLATE:READ',
  MASTER_EMAIL_SMS_TEMPLATE_UPDATE = 'MASTER_EMAIL_SMS_TEMPLATE:UPDATE',
  MASTER_EMAIL_SMS_TEMPLATE_DELETE = 'MASTER_EMAIL_SMS_TEMPLATE:DELETE',
  MASTER_EMAIL_SMS_TEMPLATE_COUNT = 'MASTER_EMAIL_SMS_TEMPLATE:COUNT',

  // master_employee_department permissions
  MASTER_EMPLOYEE_DEPARTMENT_CREATE = 'MASTER_EMPLOYEE_DEPARTMENT:CREATE',
  MASTER_EMPLOYEE_DEPARTMENT_READ = 'MASTER_EMPLOYEE_DEPARTMENT:READ',
  MASTER_EMPLOYEE_DEPARTMENT_UPDATE = 'MASTER_EMPLOYEE_DEPARTMENT:UPDATE',
  MASTER_EMPLOYEE_DEPARTMENT_DELETE = 'MASTER_EMPLOYEE_DEPARTMENT:DELETE',
  MASTER_EMPLOYEE_DEPARTMENT_COUNT = 'MASTER_EMPLOYEE_DEPARTMENT:COUNT',

  // master_employee_job_title permissions
  MASTER_EMPLOYEE_JOB_TITLE_CREATE = 'MASTER_EMPLOYEE_JOB_TITLE:CREATE',
  MASTER_EMPLOYEE_JOB_TITLE_READ = 'MASTER_EMPLOYEE_JOB_TITLE:READ',
  MASTER_EMPLOYEE_JOB_TITLE_UPDATE = 'MASTER_EMPLOYEE_JOB_TITLE:UPDATE',
  MASTER_EMPLOYEE_JOB_TITLE_DELETE = 'MASTER_EMPLOYEE_JOB_TITLE:DELETE',
  MASTER_EMPLOYEE_JOB_TITLE_COUNT = 'MASTER_EMPLOYEE_JOB_TITLE:COUNT',

  // master_employee_leave_type permissions
  MASTER_EMPLOYEE_LEAVE_TYPE_CREATE = 'MASTER_EMPLOYEE_LEAVE_TYPE:CREATE',
  MASTER_EMPLOYEE_LEAVE_TYPE_READ = 'MASTER_EMPLOYEE_LEAVE_TYPE:READ',
  MASTER_EMPLOYEE_LEAVE_TYPE_UPDATE = 'MASTER_EMPLOYEE_LEAVE_TYPE:UPDATE',
  MASTER_EMPLOYEE_LEAVE_TYPE_DELETE = 'MASTER_EMPLOYEE_LEAVE_TYPE:DELETE',
  MASTER_EMPLOYEE_LEAVE_TYPE_COUNT = 'MASTER_EMPLOYEE_LEAVE_TYPE:COUNT',

  // master_employment_status permissions
  MASTER_EMPLOYMENT_STATUS_CREATE = 'MASTER_EMPLOYMENT_STATUS:CREATE',
  MASTER_EMPLOYMENT_STATUS_READ = 'MASTER_EMPLOYMENT_STATUS:READ',
  MASTER_EMPLOYMENT_STATUS_UPDATE = 'MASTER_EMPLOYMENT_STATUS:UPDATE',
  MASTER_EMPLOYMENT_STATUS_DELETE = 'MASTER_EMPLOYMENT_STATUS:DELETE',
  MASTER_EMPLOYMENT_STATUS_COUNT = 'MASTER_EMPLOYMENT_STATUS:COUNT',

  // master_exam_difficulty_level_type permissions
  MASTER_EXAM_DIFFICULTY_LEVEL_TYPE_CREATE = 'MASTER_EXAM_DIFFICULTY_LEVEL_TYPE:CREATE',
  MASTER_EXAM_DIFFICULTY_LEVEL_TYPE_READ = 'MASTER_EXAM_DIFFICULTY_LEVEL_TYPE:READ',
  MASTER_EXAM_DIFFICULTY_LEVEL_TYPE_UPDATE = 'MASTER_EXAM_DIFFICULTY_LEVEL_TYPE:UPDATE',
  MASTER_EXAM_DIFFICULTY_LEVEL_TYPE_DELETE = 'MASTER_EXAM_DIFFICULTY_LEVEL_TYPE:DELETE',
  MASTER_EXAM_DIFFICULTY_LEVEL_TYPE_COUNT = 'MASTER_EXAM_DIFFICULTY_LEVEL_TYPE:COUNT',

  // master_exam_grade_type permissions
  MASTER_EXAM_GRADE_TYPE_CREATE = 'MASTER_EXAM_GRADE_TYPE:CREATE',
  MASTER_EXAM_GRADE_TYPE_READ = 'MASTER_EXAM_GRADE_TYPE:READ',
  MASTER_EXAM_GRADE_TYPE_UPDATE = 'MASTER_EXAM_GRADE_TYPE:UPDATE',
  MASTER_EXAM_GRADE_TYPE_DELETE = 'MASTER_EXAM_GRADE_TYPE:DELETE',
  MASTER_EXAM_GRADE_TYPE_COUNT = 'MASTER_EXAM_GRADE_TYPE:COUNT',

  // master_exam_question_answer_type permissions
  MASTER_EXAM_QUESTION_ANSWER_TYPE_CREATE = 'MASTER_EXAM_QUESTION_ANSWER_TYPE:CREATE',
  MASTER_EXAM_QUESTION_ANSWER_TYPE_READ = 'MASTER_EXAM_QUESTION_ANSWER_TYPE:READ',
  MASTER_EXAM_QUESTION_ANSWER_TYPE_UPDATE = 'MASTER_EXAM_QUESTION_ANSWER_TYPE:UPDATE',
  MASTER_EXAM_QUESTION_ANSWER_TYPE_DELETE = 'MASTER_EXAM_QUESTION_ANSWER_TYPE:DELETE',
  MASTER_EXAM_QUESTION_ANSWER_TYPE_COUNT = 'MASTER_EXAM_QUESTION_ANSWER_TYPE:COUNT',

  // master_fiscal_quarter permissions
  MASTER_FISCAL_QUARTER_CREATE = 'MASTER_FISCAL_QUARTER:CREATE',
  MASTER_FISCAL_QUARTER_READ = 'MASTER_FISCAL_QUARTER:READ',
  MASTER_FISCAL_QUARTER_UPDATE = 'MASTER_FISCAL_QUARTER:UPDATE',
  MASTER_FISCAL_QUARTER_DELETE = 'MASTER_FISCAL_QUARTER:DELETE',
  MASTER_FISCAL_QUARTER_COUNT = 'MASTER_FISCAL_QUARTER:COUNT',

  // master_institute_status permissions
  MASTER_INSTITUTE_STATUS_CREATE = 'MASTER_INSTITUTE_STATUS:CREATE',
  MASTER_INSTITUTE_STATUS_READ = 'MASTER_INSTITUTE_STATUS:READ',
  MASTER_INSTITUTE_STATUS_UPDATE = 'MASTER_INSTITUTE_STATUS:UPDATE',
  MASTER_INSTITUTE_STATUS_DELETE = 'MASTER_INSTITUTE_STATUS:DELETE',
  MASTER_INSTITUTE_STATUS_COUNT = 'MASTER_INSTITUTE_STATUS:COUNT',

  // master_job_applicant_hire_status permissions
  MASTER_JOB_APPLICANT_HIRE_STATUS_CREATE = 'MASTER_JOB_APPLICANT_HIRE_STATUS:CREATE',
  MASTER_JOB_APPLICANT_HIRE_STATUS_READ = 'MASTER_JOB_APPLICANT_HIRE_STATUS:READ',
  MASTER_JOB_APPLICANT_HIRE_STATUS_UPDATE = 'MASTER_JOB_APPLICANT_HIRE_STATUS:UPDATE',
  MASTER_JOB_APPLICANT_HIRE_STATUS_DELETE = 'MASTER_JOB_APPLICANT_HIRE_STATUS:DELETE',
  MASTER_JOB_APPLICANT_HIRE_STATUS_COUNT = 'MASTER_JOB_APPLICANT_HIRE_STATUS:COUNT',

  // master_job_status permissions
  MASTER_JOB_STATUS_CREATE = 'MASTER_JOB_STATUS:CREATE',
  MASTER_JOB_STATUS_READ = 'MASTER_JOB_STATUS:READ',
  MASTER_JOB_STATUS_UPDATE = 'MASTER_JOB_STATUS:UPDATE',
  MASTER_JOB_STATUS_DELETE = 'MASTER_JOB_STATUS:DELETE',
  MASTER_JOB_STATUS_COUNT = 'MASTER_JOB_STATUS:COUNT',

  // master_k12_grade permissions
  MASTER_K12_GRADE_CREATE = 'MASTER_K12_GRADE:CREATE',
  MASTER_K12_GRADE_READ = 'MASTER_K12_GRADE:READ',
  MASTER_K12_GRADE_UPDATE = 'MASTER_K12_GRADE:UPDATE',
  MASTER_K12_GRADE_DELETE = 'MASTER_K12_GRADE:DELETE',
  MASTER_K12_GRADE_COUNT = 'MASTER_K12_GRADE:COUNT',

  // master_language permissions
  MASTER_LANGUAGE_CREATE = 'MASTER_LANGUAGE:CREATE',
  MASTER_LANGUAGE_READ = 'MASTER_LANGUAGE:READ',
  MASTER_LANGUAGE_UPDATE = 'MASTER_LANGUAGE:UPDATE',
  MASTER_LANGUAGE_DELETE = 'MASTER_LANGUAGE:DELETE',
  MASTER_LANGUAGE_COUNT = 'MASTER_LANGUAGE:COUNT',

  // master_lead_source_channel permissions
  MASTER_LEAD_SOURCE_CHANNEL_CREATE = 'MASTER_LEAD_SOURCE_CHANNEL:CREATE',
  MASTER_LEAD_SOURCE_CHANNEL_READ = 'MASTER_LEAD_SOURCE_CHANNEL:READ',
  MASTER_LEAD_SOURCE_CHANNEL_UPDATE = 'MASTER_LEAD_SOURCE_CHANNEL:UPDATE',
  MASTER_LEAD_SOURCE_CHANNEL_DELETE = 'MASTER_LEAD_SOURCE_CHANNEL:DELETE',
  MASTER_LEAD_SOURCE_CHANNEL_COUNT = 'MASTER_LEAD_SOURCE_CHANNEL:COUNT',

  // master_lead_status permissions
  MASTER_LEAD_STATUS_CREATE = 'MASTER_LEAD_STATUS:CREATE',
  MASTER_LEAD_STATUS_READ = 'MASTER_LEAD_STATUS:READ',
  MASTER_LEAD_STATUS_UPDATE = 'MASTER_LEAD_STATUS:UPDATE',
  MASTER_LEAD_STATUS_DELETE = 'MASTER_LEAD_STATUS:DELETE',
  MASTER_LEAD_STATUS_COUNT = 'MASTER_LEAD_STATUS:COUNT',

  // master_membership_type permissions
  MASTER_MEMBERSHIP_TYPE_CREATE = 'MASTER_MEMBERSHIP_TYPE:CREATE',
  MASTER_MEMBERSHIP_TYPE_READ = 'MASTER_MEMBERSHIP_TYPE:READ',
  MASTER_MEMBERSHIP_TYPE_UPDATE = 'MASTER_MEMBERSHIP_TYPE:UPDATE',
  MASTER_MEMBERSHIP_TYPE_DELETE = 'MASTER_MEMBERSHIP_TYPE:DELETE',
  MASTER_MEMBERSHIP_TYPE_COUNT = 'MASTER_MEMBERSHIP_TYPE:COUNT',

  // master_order_channel_type permissions
  MASTER_ORDER_CHANNEL_TYPE_CREATE = 'MASTER_ORDER_CHANNEL_TYPE:CREATE',
  MASTER_ORDER_CHANNEL_TYPE_READ = 'MASTER_ORDER_CHANNEL_TYPE:READ',
  MASTER_ORDER_CHANNEL_TYPE_UPDATE = 'MASTER_ORDER_CHANNEL_TYPE:UPDATE',
  MASTER_ORDER_CHANNEL_TYPE_DELETE = 'MASTER_ORDER_CHANNEL_TYPE:DELETE',
  MASTER_ORDER_CHANNEL_TYPE_COUNT = 'MASTER_ORDER_CHANNEL_TYPE:COUNT',

  // master_order_payment_type permissions
  MASTER_ORDER_PAYMENT_TYPE_CREATE = 'MASTER_ORDER_PAYMENT_TYPE:CREATE',
  MASTER_ORDER_PAYMENT_TYPE_READ = 'MASTER_ORDER_PAYMENT_TYPE:READ',
  MASTER_ORDER_PAYMENT_TYPE_UPDATE = 'MASTER_ORDER_PAYMENT_TYPE:UPDATE',
  MASTER_ORDER_PAYMENT_TYPE_DELETE = 'MASTER_ORDER_PAYMENT_TYPE:DELETE',
  MASTER_ORDER_PAYMENT_TYPE_COUNT = 'MASTER_ORDER_PAYMENT_TYPE:COUNT',

  // master_order_status_type permissions
  MASTER_ORDER_STATUS_TYPE_CREATE = 'MASTER_ORDER_STATUS_TYPE:CREATE',
  MASTER_ORDER_STATUS_TYPE_READ = 'MASTER_ORDER_STATUS_TYPE:READ',
  MASTER_ORDER_STATUS_TYPE_UPDATE = 'MASTER_ORDER_STATUS_TYPE:UPDATE',
  MASTER_ORDER_STATUS_TYPE_DELETE = 'MASTER_ORDER_STATUS_TYPE:DELETE',
  MASTER_ORDER_STATUS_TYPE_COUNT = 'MASTER_ORDER_STATUS_TYPE:COUNT',

  // master_photo_library permissions
  MASTER_PHOTO_LIBRARY_CREATE = 'MASTER_PHOTO_LIBRARY:CREATE',
  MASTER_PHOTO_LIBRARY_READ = 'MASTER_PHOTO_LIBRARY:READ',
  MASTER_PHOTO_LIBRARY_UPDATE = 'MASTER_PHOTO_LIBRARY:UPDATE',
  MASTER_PHOTO_LIBRARY_DELETE = 'MASTER_PHOTO_LIBRARY:DELETE',
  MASTER_PHOTO_LIBRARY_COUNT = 'MASTER_PHOTO_LIBRARY:COUNT',

  // master_proposal_template permissions
  MASTER_PROPOSAL_TEMPLATE_CREATE = 'MASTER_PROPOSAL_TEMPLATE:CREATE',
  MASTER_PROPOSAL_TEMPLATE_READ = 'MASTER_PROPOSAL_TEMPLATE:READ',
  MASTER_PROPOSAL_TEMPLATE_UPDATE = 'MASTER_PROPOSAL_TEMPLATE:UPDATE',
  MASTER_PROPOSAL_TEMPLATE_DELETE = 'MASTER_PROPOSAL_TEMPLATE:DELETE',
  MASTER_PROPOSAL_TEMPLATE_COUNT = 'MASTER_PROPOSAL_TEMPLATE:COUNT',

  // master_salary_pay_frequency permissions
  MASTER_SALARY_PAY_FREQUENCY_CREATE = 'MASTER_SALARY_PAY_FREQUENCY:CREATE',
  MASTER_SALARY_PAY_FREQUENCY_READ = 'MASTER_SALARY_PAY_FREQUENCY:READ',
  MASTER_SALARY_PAY_FREQUENCY_UPDATE = 'MASTER_SALARY_PAY_FREQUENCY:UPDATE',
  MASTER_SALARY_PAY_FREQUENCY_DELETE = 'MASTER_SALARY_PAY_FREQUENCY:DELETE',
  MASTER_SALARY_PAY_FREQUENCY_COUNT = 'MASTER_SALARY_PAY_FREQUENCY:COUNT',

  // master_salary_type permissions
  MASTER_SALARY_TYPE_CREATE = 'MASTER_SALARY_TYPE:CREATE',
  MASTER_SALARY_TYPE_READ = 'MASTER_SALARY_TYPE:READ',
  MASTER_SALARY_TYPE_UPDATE = 'MASTER_SALARY_TYPE:UPDATE',
  MASTER_SALARY_TYPE_DELETE = 'MASTER_SALARY_TYPE:DELETE',
  MASTER_SALARY_TYPE_COUNT = 'MASTER_SALARY_TYPE:COUNT',

  // master_scholarship_application_status permissions
  MASTER_SCHOLARSHIP_APPLICATION_STATUS_CREATE = 'MASTER_SCHOLARSHIP_APPLICATION_STATUS:CREATE',
  MASTER_SCHOLARSHIP_APPLICATION_STATUS_READ = 'MASTER_SCHOLARSHIP_APPLICATION_STATUS:READ',
  MASTER_SCHOLARSHIP_APPLICATION_STATUS_UPDATE = 'MASTER_SCHOLARSHIP_APPLICATION_STATUS:UPDATE',
  MASTER_SCHOLARSHIP_APPLICATION_STATUS_DELETE = 'MASTER_SCHOLARSHIP_APPLICATION_STATUS:DELETE',
  MASTER_SCHOLARSHIP_APPLICATION_STATUS_COUNT = 'MASTER_SCHOLARSHIP_APPLICATION_STATUS:COUNT',

  // master_scholarship_type permissions
  MASTER_SCHOLARSHIP_TYPE_CREATE = 'MASTER_SCHOLARSHIP_TYPE:CREATE',
  MASTER_SCHOLARSHIP_TYPE_READ = 'MASTER_SCHOLARSHIP_TYPE:READ',
  MASTER_SCHOLARSHIP_TYPE_UPDATE = 'MASTER_SCHOLARSHIP_TYPE:UPDATE',
  MASTER_SCHOLARSHIP_TYPE_DELETE = 'MASTER_SCHOLARSHIP_TYPE:DELETE',
  MASTER_SCHOLARSHIP_TYPE_COUNT = 'MASTER_SCHOLARSHIP_TYPE:COUNT',

  // master_state permissions
  MASTER_STATE_CREATE = 'MASTER_STATE:CREATE',
  MASTER_STATE_READ = 'MASTER_STATE:READ',
  MASTER_STATE_UPDATE = 'MASTER_STATE:UPDATE',
  MASTER_STATE_DELETE = 'MASTER_STATE:DELETE',
  MASTER_STATE_COUNT = 'MASTER_STATE:COUNT',

  // master_store_type permissions
  MASTER_STORE_TYPE_CREATE = 'MASTER_STORE_TYPE:CREATE',
  MASTER_STORE_TYPE_READ = 'MASTER_STORE_TYPE:READ',
  MASTER_STORE_TYPE_UPDATE = 'MASTER_STORE_TYPE:UPDATE',
  MASTER_STORE_TYPE_DELETE = 'MASTER_STORE_TYPE:DELETE',
  MASTER_STORE_TYPE_COUNT = 'MASTER_STORE_TYPE:COUNT',

  // master_student_course_completion_status permissions
  MASTER_STUDENT_COURSE_COMPLETION_STATUS_CREATE = 'MASTER_STUDENT_COURSE_COMPLETION_STATUS:CREATE',
  MASTER_STUDENT_COURSE_COMPLETION_STATUS_READ = 'MASTER_STUDENT_COURSE_COMPLETION_STATUS:READ',
  MASTER_STUDENT_COURSE_COMPLETION_STATUS_UPDATE = 'MASTER_STUDENT_COURSE_COMPLETION_STATUS:UPDATE',
  MASTER_STUDENT_COURSE_COMPLETION_STATUS_DELETE = 'MASTER_STUDENT_COURSE_COMPLETION_STATUS:DELETE',
  MASTER_STUDENT_COURSE_COMPLETION_STATUS_COUNT = 'MASTER_STUDENT_COURSE_COMPLETION_STATUS:COUNT',

  // master_subscription_duration_type permissions
  MASTER_SUBSCRIPTION_DURATION_TYPE_CREATE = 'MASTER_SUBSCRIPTION_DURATION_TYPE:CREATE',
  MASTER_SUBSCRIPTION_DURATION_TYPE_READ = 'MASTER_SUBSCRIPTION_DURATION_TYPE:READ',
  MASTER_SUBSCRIPTION_DURATION_TYPE_UPDATE = 'MASTER_SUBSCRIPTION_DURATION_TYPE:UPDATE',
  MASTER_SUBSCRIPTION_DURATION_TYPE_DELETE = 'MASTER_SUBSCRIPTION_DURATION_TYPE:DELETE',
  MASTER_SUBSCRIPTION_DURATION_TYPE_COUNT = 'MASTER_SUBSCRIPTION_DURATION_TYPE:COUNT',

  // master_tag_category permissions
  MASTER_TAG_CATEGORY_CREATE = 'MASTER_TAG_CATEGORY:CREATE',
  MASTER_TAG_CATEGORY_READ = 'MASTER_TAG_CATEGORY:READ',
  MASTER_TAG_CATEGORY_UPDATE = 'MASTER_TAG_CATEGORY:UPDATE',
  MASTER_TAG_CATEGORY_DELETE = 'MASTER_TAG_CATEGORY:DELETE',
  MASTER_TAG_CATEGORY_COUNT = 'MASTER_TAG_CATEGORY:COUNT',

  // master_tag permissions
  MASTER_TAG_CREATE = 'MASTER_TAG:CREATE',
  MASTER_TAG_READ = 'MASTER_TAG:READ',
  MASTER_TAG_UPDATE = 'MASTER_TAG:UPDATE',
  MASTER_TAG_DELETE = 'MASTER_TAG:DELETE',
  MASTER_TAG_COUNT = 'MASTER_TAG:COUNT',

  // master_task_status permissions
  MASTER_TASK_STATUS_CREATE = 'MASTER_TASK_STATUS:CREATE',
  MASTER_TASK_STATUS_READ = 'MASTER_TASK_STATUS:READ',
  MASTER_TASK_STATUS_UPDATE = 'MASTER_TASK_STATUS:UPDATE',
  MASTER_TASK_STATUS_DELETE = 'MASTER_TASK_STATUS:DELETE',
  MASTER_TASK_STATUS_COUNT = 'MASTER_TASK_STATUS:COUNT',

  // master_task_template permissions
  MASTER_TASK_TEMPLATE_CREATE = 'MASTER_TASK_TEMPLATE:CREATE',
  MASTER_TASK_TEMPLATE_READ = 'MASTER_TASK_TEMPLATE:READ',
  MASTER_TASK_TEMPLATE_UPDATE = 'MASTER_TASK_TEMPLATE:UPDATE',
  MASTER_TASK_TEMPLATE_DELETE = 'MASTER_TASK_TEMPLATE:DELETE',
  MASTER_TASK_TEMPLATE_COUNT = 'MASTER_TASK_TEMPLATE:COUNT',

  // master_tutoring_session_status permissions
  MASTER_TUTORING_SESSION_STATUS_CREATE = 'MASTER_TUTORING_SESSION_STATUS:CREATE',
  MASTER_TUTORING_SESSION_STATUS_READ = 'MASTER_TUTORING_SESSION_STATUS:READ',
  MASTER_TUTORING_SESSION_STATUS_UPDATE = 'MASTER_TUTORING_SESSION_STATUS:UPDATE',
  MASTER_TUTORING_SESSION_STATUS_DELETE = 'MASTER_TUTORING_SESSION_STATUS:DELETE',
  MASTER_TUTORING_SESSION_STATUS_COUNT = 'MASTER_TUTORING_SESSION_STATUS:COUNT',

  // master_user_sign_and_opt_out_link permissions
  MASTER_USER_SIGN_AND_OPT_OUT_LINK_CREATE = 'MASTER_USER_SIGN_AND_OPT_OUT_LINK:CREATE',
  MASTER_USER_SIGN_AND_OPT_OUT_LINK_READ = 'MASTER_USER_SIGN_AND_OPT_OUT_LINK:READ',
  MASTER_USER_SIGN_AND_OPT_OUT_LINK_UPDATE = 'MASTER_USER_SIGN_AND_OPT_OUT_LINK:UPDATE',
  MASTER_USER_SIGN_AND_OPT_OUT_LINK_DELETE = 'MASTER_USER_SIGN_AND_OPT_OUT_LINK:DELETE',
  MASTER_USER_SIGN_AND_OPT_OUT_LINK_COUNT = 'MASTER_USER_SIGN_AND_OPT_OUT_LINK:COUNT',

  // master_video_library permissions
  MASTER_VIDEO_LIBRARY_CREATE = 'MASTER_VIDEO_LIBRARY:CREATE',
  MASTER_VIDEO_LIBRARY_READ = 'MASTER_VIDEO_LIBRARY:READ',
  MASTER_VIDEO_LIBRARY_UPDATE = 'MASTER_VIDEO_LIBRARY:UPDATE',
  MASTER_VIDEO_LIBRARY_DELETE = 'MASTER_VIDEO_LIBRARY:DELETE',
  MASTER_VIDEO_LIBRARY_COUNT = 'MASTER_VIDEO_LIBRARY:COUNT',

  // master_website_content permissions
  MASTER_WEBSITE_CONTENT_CREATE = 'MASTER_WEBSITE_CONTENT:CREATE',
  MASTER_WEBSITE_CONTENT_READ = 'MASTER_WEBSITE_CONTENT:READ',
  MASTER_WEBSITE_CONTENT_UPDATE = 'MASTER_WEBSITE_CONTENT:UPDATE',
  MASTER_WEBSITE_CONTENT_DELETE = 'MASTER_WEBSITE_CONTENT:DELETE',
  MASTER_WEBSITE_CONTENT_COUNT = 'MASTER_WEBSITE_CONTENT:COUNT',

  // master_work_day_type permissions
  MASTER_WORK_DAY_TYPE_CREATE = 'MASTER_WORK_DAY_TYPE:CREATE',
  MASTER_WORK_DAY_TYPE_READ = 'MASTER_WORK_DAY_TYPE:READ',
  MASTER_WORK_DAY_TYPE_UPDATE = 'MASTER_WORK_DAY_TYPE:UPDATE',
  MASTER_WORK_DAY_TYPE_DELETE = 'MASTER_WORK_DAY_TYPE:DELETE',
  MASTER_WORK_DAY_TYPE_COUNT = 'MASTER_WORK_DAY_TYPE:COUNT',

  // master_zip_code permissions
  MASTER_ZIP_CODE_CREATE = 'MASTER_ZIP_CODE:CREATE',
  MASTER_ZIP_CODE_READ = 'MASTER_ZIP_CODE:READ',
  MASTER_ZIP_CODE_UPDATE = 'MASTER_ZIP_CODE:UPDATE',
  MASTER_ZIP_CODE_DELETE = 'MASTER_ZIP_CODE:DELETE',
  MASTER_ZIP_CODE_COUNT = 'MASTER_ZIP_CODE:COUNT',

  // master_zone_type permissions
  MASTER_ZONE_TYPE_CREATE = 'MASTER_ZONE_TYPE:CREATE',
  MASTER_ZONE_TYPE_READ = 'MASTER_ZONE_TYPE:READ',
  MASTER_ZONE_TYPE_UPDATE = 'MASTER_ZONE_TYPE:UPDATE',
  MASTER_ZONE_TYPE_DELETE = 'MASTER_ZONE_TYPE:DELETE',
  MASTER_ZONE_TYPE_COUNT = 'MASTER_ZONE_TYPE:COUNT',

  // master_learning_goals permissions
  MASTER_LEARNING_GOAL_CREATE = 'MASTER_LEARNING_GOAL:CREATE',
  MASTER_LEARNING_GOAL_READ = 'MASTER_LEARNING_GOAL:READ',
  MASTER_LEARNING_GOAL_UPDATE = 'MASTER_LEARNING_GOAL:UPDATE',
  MASTER_LEARNING_GOAL_DELETE = 'MASTER_LEARNING_GOAL:DELETE',
  MASTER_LEARNING_GOAL_COUNT = 'MASTER_LEARNING_GOAL:COUNT',

  // app_notification permissions
  APP_NOTIFICATION_CREATE = 'APP_NOTIFICATION:CREATE',
  APP_NOTIFICATION_READ = 'APP_NOTIFICATION:READ',
  APP_NOTIFICATION_UPDATE = 'APP_NOTIFICATION:UPDATE',
  APP_NOTIFICATION_DELETE = 'APP_NOTIFICATION:DELETE',
  APP_NOTIFICATION_COUNT = 'APP_NOTIFICATION:COUNT',

  // app_permission permissions
  APP_PERMISSION_CREATE = 'APP_PERMISSION:CREATE',
  APP_PERMISSION_READ = 'APP_PERMISSION:READ',
  APP_PERMISSION_UPDATE = 'APP_PERMISSION:UPDATE',
  APP_PERMISSION_DELETE = 'APP_PERMISSION:DELETE',
  APP_PERMISSION_COUNT = 'APP_PERMISSION:COUNT',

  // app_role_permission permissions
  APP_ROLE_PERMISSION_CREATE = 'APP_ROLE_PERMISSION:CREATE',
  APP_ROLE_PERMISSION_READ = 'APP_ROLE_PERMISSION:READ',
  APP_ROLE_PERMISSION_UPDATE = 'APP_ROLE_PERMISSION:UPDATE',
  APP_ROLE_PERMISSION_DELETE = 'APP_ROLE_PERMISSION:DELETE',
  APP_ROLE_PERMISSION_COUNT = 'APP_ROLE_PERMISSION:COUNT',

  // app_role permissions
  APP_ROLE_CREATE = 'APP_ROLE:CREATE',
  APP_ROLE_READ = 'APP_ROLE:READ',
  APP_ROLE_UPDATE = 'APP_ROLE:UPDATE',
  APP_ROLE_DELETE = 'APP_ROLE:DELETE',
  APP_ROLE_COUNT = 'APP_ROLE:COUNT',

  // app_user_custom_permission permissions
  APP_USER_CUSTOM_PERMISSION_CREATE = 'APP_USER_CUSTOM_PERMISSION:CREATE',
  APP_USER_CUSTOM_PERMISSION_READ = 'APP_USER_CUSTOM_PERMISSION:READ',
  APP_USER_CUSTOM_PERMISSION_UPDATE = 'APP_USER_CUSTOM_PERMISSION:UPDATE',
  APP_USER_CUSTOM_PERMISSION_DELETE = 'APP_USER_CUSTOM_PERMISSION:DELETE',
  APP_USER_CUSTOM_PERMISSION_COUNT = 'APP_USER_CUSTOM_PERMISSION:COUNT',

  // app_user_role permissions
  APP_USER_ROLE_CREATE = 'APP_USER_ROLE:CREATE',
  APP_USER_ROLE_READ = 'APP_USER_ROLE:READ',
  APP_USER_ROLE_UPDATE = 'APP_USER_ROLE:UPDATE',
  APP_USER_ROLE_DELETE = 'APP_USER_ROLE:DELETE',
  APP_USER_ROLE_COUNT = 'APP_USER_ROLE:COUNT',

  // app_user permissions
  APP_USER_CREATE = 'APP_USER:CREATE',
  APP_USER_READ = 'APP_USER:READ',
  APP_USER_UPDATE = 'APP_USER:UPDATE',
  APP_USER_DELETE = 'APP_USER:DELETE',
  APP_USER_COUNT = 'APP_USER:COUNT',

  // zone_account_team permissions
  ZONE_ACCOUNT_TEAM_CREATE = 'ZONE_ACCOUNT_TEAM:CREATE',
  ZONE_ACCOUNT_TEAM_READ = 'ZONE_ACCOUNT_TEAM:READ',
  ZONE_ACCOUNT_TEAM_UPDATE = 'ZONE_ACCOUNT_TEAM:UPDATE',
  ZONE_ACCOUNT_TEAM_DELETE = 'ZONE_ACCOUNT_TEAM:DELETE',
  ZONE_ACCOUNT_TEAM_COUNT = 'ZONE_ACCOUNT_TEAM:COUNT',

  // zone_area_by_zipcode permissions
  ZONE_AREA_BY_ZIPCODE_CREATE = 'ZONE_AREA_BY_ZIPCODE:CREATE',
  ZONE_AREA_BY_ZIPCODE_READ = 'ZONE_AREA_BY_ZIPCODE:READ',
  ZONE_AREA_BY_ZIPCODE_UPDATE = 'ZONE_AREA_BY_ZIPCODE:UPDATE',
  ZONE_AREA_BY_ZIPCODE_DELETE = 'ZONE_AREA_BY_ZIPCODE:DELETE',
  ZONE_AREA_BY_ZIPCODE_COUNT = 'ZONE_AREA_BY_ZIPCODE:COUNT',

  // zone_company permissions
  ZONE_COMPANY_CREATE = 'ZONE_COMPANY:CREATE',
  ZONE_COMPANY_READ = 'ZONE_COMPANY:READ',
  ZONE_COMPANY_UPDATE = 'ZONE_COMPANY:UPDATE',
  ZONE_COMPANY_DELETE = 'ZONE_COMPANY:DELETE',
  ZONE_COMPANY_COUNT = 'ZONE_COMPANY:COUNT',

  // zone_contact permissions
  ZONE_CONTACT_CREATE = 'ZONE_CONTACT:CREATE',
  ZONE_CONTACT_READ = 'ZONE_CONTACT:READ',
  ZONE_CONTACT_UPDATE = 'ZONE_CONTACT:UPDATE',
  ZONE_CONTACT_DELETE = 'ZONE_CONTACT:DELETE',
  ZONE_CONTACT_COUNT = 'ZONE_CONTACT:COUNT',

  // zone_course_category permissions
  ZONE_COURSE_CATEGORY_CREATE = 'ZONE_COURSE_CATEGORY:CREATE',
  ZONE_COURSE_CATEGORY_READ = 'ZONE_COURSE_CATEGORY:READ',
  ZONE_COURSE_CATEGORY_UPDATE = 'ZONE_COURSE_CATEGORY:UPDATE',
  ZONE_COURSE_CATEGORY_DELETE = 'ZONE_COURSE_CATEGORY:DELETE',
  ZONE_COURSE_CATEGORY_COUNT = 'ZONE_COURSE_CATEGORY:COUNT',

  // zone_course permissions
  ZONE_COURSE_CREATE = 'ZONE_COURSE:CREATE',
  ZONE_COURSE_READ = 'ZONE_COURSE:READ',
  ZONE_COURSE_UPDATE = 'ZONE_COURSE:UPDATE',
  ZONE_COURSE_DELETE = 'ZONE_COURSE:DELETE',
  ZONE_COURSE_COUNT = 'ZONE_COURSE:COUNT',

  // zone_institute permissions
  ZONE_INSTITUTE_CREATE = 'ZONE_INSTITUTE:CREATE',
  ZONE_INSTITUTE_READ = 'ZONE_INSTITUTE:READ',
  ZONE_INSTITUTE_UPDATE = 'ZONE_INSTITUTE:UPDATE',
  ZONE_INSTITUTE_DELETE = 'ZONE_INSTITUTE:DELETE',
  ZONE_INSTITUTE_COUNT = 'ZONE_INSTITUTE:COUNT',

  // zone_job permissions
  ZONE_JOB_CREATE = 'ZONE_JOB:CREATE',
  ZONE_JOB_READ = 'ZONE_JOB:READ',
  ZONE_JOB_UPDATE = 'ZONE_JOB:UPDATE',
  ZONE_JOB_DELETE = 'ZONE_JOB:DELETE',
  ZONE_JOB_COUNT = 'ZONE_JOB:COUNT',

  // zone_product_category permissions
  ZONE_PRODUCT_CATEGORY_CREATE = 'ZONE_PRODUCT_CATEGORY:CREATE',
  ZONE_PRODUCT_CATEGORY_READ = 'ZONE_PRODUCT_CATEGORY:READ',
  ZONE_PRODUCT_CATEGORY_UPDATE = 'ZONE_PRODUCT_CATEGORY:UPDATE',
  ZONE_PRODUCT_CATEGORY_DELETE = 'ZONE_PRODUCT_CATEGORY:DELETE',
  ZONE_PRODUCT_CATEGORY_COUNT = 'ZONE_PRODUCT_CATEGORY:COUNT',

  // zone_product permissions
  ZONE_PRODUCT_CREATE = 'ZONE_PRODUCT:CREATE',
  ZONE_PRODUCT_READ = 'ZONE_PRODUCT:READ',
  ZONE_PRODUCT_UPDATE = 'ZONE_PRODUCT:UPDATE',
  ZONE_PRODUCT_DELETE = 'ZONE_PRODUCT:DELETE',
  ZONE_PRODUCT_COUNT = 'ZONE_PRODUCT:COUNT',

  // zone_sales_projection permissions
  ZONE_SALES_PROJECTION_CREATE = 'ZONE_SALES_PROJECTION:CREATE',
  ZONE_SALES_PROJECTION_READ = 'ZONE_SALES_PROJECTION:READ',
  ZONE_SALES_PROJECTION_UPDATE = 'ZONE_SALES_PROJECTION:UPDATE',
  ZONE_SALES_PROJECTION_DELETE = 'ZONE_SALES_PROJECTION:DELETE',
  ZONE_SALES_PROJECTION_COUNT = 'ZONE_SALES_PROJECTION:COUNT',

  // zone_scholarship permissions
  ZONE_SCHOLARSHIP_CREATE = 'ZONE_SCHOLARSHIP:CREATE',
  ZONE_SCHOLARSHIP_READ = 'ZONE_SCHOLARSHIP:READ',
  ZONE_SCHOLARSHIP_UPDATE = 'ZONE_SCHOLARSHIP:UPDATE',
  ZONE_SCHOLARSHIP_DELETE = 'ZONE_SCHOLARSHIP:DELETE',
  ZONE_SCHOLARSHIP_COUNT = 'ZONE_SCHOLARSHIP:COUNT',

  // zone_store permissions
  ZONE_STORE_CREATE = 'ZONE_STORE:CREATE',
  ZONE_STORE_READ = 'ZONE_STORE:READ',
  ZONE_STORE_UPDATE = 'ZONE_STORE:UPDATE',
  ZONE_STORE_DELETE = 'ZONE_STORE:DELETE',
  ZONE_STORE_COUNT = 'ZONE_STORE:COUNT',

  // zone_student permissions
  ZONE_STUDENT_CREATE = 'ZONE_STUDENT:CREATE',
  ZONE_STUDENT_READ = 'ZONE_STUDENT:READ',
  ZONE_STUDENT_UPDATE = 'ZONE_STUDENT:UPDATE',
  ZONE_STUDENT_DELETE = 'ZONE_STUDENT:DELETE',
  ZONE_STUDENT_COUNT = 'ZONE_STUDENT:COUNT',

  // zone_tutor permissions
  ZONE_TUTOR_CREATE = 'ZONE_TUTOR:CREATE',
  ZONE_TUTOR_READ = 'ZONE_TUTOR:READ',
  ZONE_TUTOR_UPDATE = 'ZONE_TUTOR:UPDATE',
  ZONE_TUTOR_DELETE = 'ZONE_TUTOR:DELETE',
  ZONE_TUTOR_COUNT = 'ZONE_TUTOR:COUNT',

  // zone permissions
  ZONE_CREATE = 'ZONE:CREATE',
  ZONE_READ = 'ZONE:READ',
  ZONE_UPDATE = 'ZONE:UPDATE',
  ZONE_DELETE = 'ZONE:DELETE',
  ZONE_COUNT = 'ZONE:COUNT',

  // task_document permissions
  TASK_DOCUMENT_CREATE = 'TASK_DOCUMENT:CREATE',
  TASK_DOCUMENT_READ = 'TASK_DOCUMENT:READ',
  TASK_DOCUMENT_UPDATE = 'TASK_DOCUMENT:UPDATE',
  TASK_DOCUMENT_DELETE = 'TASK_DOCUMENT:DELETE',
  TASK_DOCUMENT_COUNT = 'TASK_DOCUMENT:COUNT',

  // task_event permissions
  TASK_EVENT_CREATE = 'TASK_EVENT:CREATE',
  TASK_EVENT_READ = 'TASK_EVENT:READ',
  TASK_EVENT_UPDATE = 'TASK_EVENT:UPDATE',
  TASK_EVENT_DELETE = 'TASK_EVENT:DELETE',
  TASK_EVENT_COUNT = 'TASK_EVENT:COUNT',

  // task_meeting_team permissions
  TASK_MEETING_TEAM_CREATE = 'TASK_MEETING_TEAM:CREATE',
  TASK_MEETING_TEAM_READ = 'TASK_MEETING_TEAM:READ',
  TASK_MEETING_TEAM_UPDATE = 'TASK_MEETING_TEAM:UPDATE',
  TASK_MEETING_TEAM_DELETE = 'TASK_MEETING_TEAM:DELETE',
  TASK_MEETING_TEAM_COUNT = 'TASK_MEETING_TEAM:COUNT',

  // task_note permissions
  TASK_NOTE_CREATE = 'TASK_NOTE:CREATE',
  TASK_NOTE_READ = 'TASK_NOTE:READ',
  TASK_NOTE_UPDATE = 'TASK_NOTE:UPDATE',
  TASK_NOTE_DELETE = 'TASK_NOTE:DELETE',
  TASK_NOTE_COUNT = 'TASK_NOTE:COUNT',

  // task_reference permissions
  TASK_REFERENCE_CREATE = 'TASK_REFERENCE:CREATE',
  TASK_REFERENCE_READ = 'TASK_REFERENCE:READ',
  TASK_REFERENCE_UPDATE = 'TASK_REFERENCE:UPDATE',
  TASK_REFERENCE_DELETE = 'TASK_REFERENCE:DELETE',
  TASK_REFERENCE_COUNT = 'TASK_REFERENCE:COUNT',

  // task_work_item permissions
  TASK_WORK_ITEM_CREATE = 'TASK_WORK_ITEM:CREATE',
  TASK_WORK_ITEM_READ = 'TASK_WORK_ITEM:READ',
  TASK_WORK_ITEM_UPDATE = 'TASK_WORK_ITEM:UPDATE',
  TASK_WORK_ITEM_DELETE = 'TASK_WORK_ITEM:DELETE',
  TASK_WORK_ITEM_COUNT = 'TASK_WORK_ITEM:COUNT',

  // employee_attendance permissions
  EMPLOYEE_ATTENDANCE_CREATE = 'EMPLOYEE_ATTENDANCE:CREATE',
  EMPLOYEE_ATTENDANCE_READ = 'EMPLOYEE_ATTENDANCE:READ',
  EMPLOYEE_ATTENDANCE_UPDATE = 'EMPLOYEE_ATTENDANCE:UPDATE',
  EMPLOYEE_ATTENDANCE_DELETE = 'EMPLOYEE_ATTENDANCE:DELETE',
  EMPLOYEE_ATTENDANCE_COUNT = 'EMPLOYEE_ATTENDANCE:COUNT',

  // employee_leave permissions
  EMPLOYEE_LEAVE_CREATE = 'EMPLOYEE_LEAVE:CREATE',
  EMPLOYEE_LEAVE_READ = 'EMPLOYEE_LEAVE:READ',
  EMPLOYEE_LEAVE_UPDATE = 'EMPLOYEE_LEAVE:UPDATE',
  EMPLOYEE_LEAVE_DELETE = 'EMPLOYEE_LEAVE:DELETE',
  EMPLOYEE_LEAVE_COUNT = 'EMPLOYEE_LEAVE:COUNT',

  // employee_performance_review permissions
  EMPLOYEE_PERFORMANCE_REVIEW_CREATE = 'EMPLOYEE_PERFORMANCE_REVIEW:CREATE',
  EMPLOYEE_PERFORMANCE_REVIEW_READ = 'EMPLOYEE_PERFORMANCE_REVIEW:READ',
  EMPLOYEE_PERFORMANCE_REVIEW_UPDATE = 'EMPLOYEE_PERFORMANCE_REVIEW:UPDATE',
  EMPLOYEE_PERFORMANCE_REVIEW_DELETE = 'EMPLOYEE_PERFORMANCE_REVIEW:DELETE',
  EMPLOYEE_PERFORMANCE_REVIEW_COUNT = 'EMPLOYEE_PERFORMANCE_REVIEW:COUNT',

  // employee_salary_compensation permissions
  EMPLOYEE_SALARY_COMPENSATION_CREATE = 'EMPLOYEE_SALARY_COMPENSATION:CREATE',
  EMPLOYEE_SALARY_COMPENSATION_READ = 'EMPLOYEE_SALARY_COMPENSATION:READ',
  EMPLOYEE_SALARY_COMPENSATION_UPDATE = 'EMPLOYEE_SALARY_COMPENSATION:UPDATE',
  EMPLOYEE_SALARY_COMPENSATION_DELETE = 'EMPLOYEE_SALARY_COMPENSATION:DELETE',
  EMPLOYEE_SALARY_COMPENSATION_COUNT = 'EMPLOYEE_SALARY_COMPENSATION:COUNT',

  // employee_tag permissions
  EMPLOYEE_TAG_CREATE = 'EMPLOYEE_TAG:CREATE',
  EMPLOYEE_TAG_READ = 'EMPLOYEE_TAG:READ',
  EMPLOYEE_TAG_UPDATE = 'EMPLOYEE_TAG:UPDATE',
  EMPLOYEE_TAG_DELETE = 'EMPLOYEE_TAG:DELETE',
  EMPLOYEE_TAG_COUNT = 'EMPLOYEE_TAG:COUNT',

  // employee_training permissions
  EMPLOYEE_TRAINING_CREATE = 'EMPLOYEE_TRAINING:CREATE',
  EMPLOYEE_TRAINING_READ = 'EMPLOYEE_TRAINING:READ',
  EMPLOYEE_TRAINING_UPDATE = 'EMPLOYEE_TRAINING:UPDATE',
  EMPLOYEE_TRAINING_DELETE = 'EMPLOYEE_TRAINING:DELETE',
  EMPLOYEE_TRAINING_COUNT = 'EMPLOYEE_TRAINING:COUNT',

  // employee_weekly_work_schedule permissions
  EMPLOYEE_WEEKLY_WORK_SCHEDULE_CREATE = 'EMPLOYEE_WEEKLY_WORK_SCHEDULE:CREATE',
  EMPLOYEE_WEEKLY_WORK_SCHEDULE_READ = 'EMPLOYEE_WEEKLY_WORK_SCHEDULE:READ',
  EMPLOYEE_WEEKLY_WORK_SCHEDULE_UPDATE = 'EMPLOYEE_WEEKLY_WORK_SCHEDULE:UPDATE',
  EMPLOYEE_WEEKLY_WORK_SCHEDULE_DELETE = 'EMPLOYEE_WEEKLY_WORK_SCHEDULE:DELETE',
  EMPLOYEE_WEEKLY_WORK_SCHEDULE_COUNT = 'EMPLOYEE_WEEKLY_WORK_SCHEDULE:COUNT',

  // employee_work_attendance_policy_acknowledgement permissions
  EMPLOYEE_WORK_ATTENDANCE_POLICY_ACKNOWLEDGEMENT_CREATE = 'EMPLOYEE_WORK_ATTENDANCE_POLICY_ACKNOWLEDGEMENT:CREATE',
  EMPLOYEE_WORK_ATTENDANCE_POLICY_ACKNOWLEDGEMENT_READ = 'EMPLOYEE_WORK_ATTENDANCE_POLICY_ACKNOWLEDGEMENT:READ',
  EMPLOYEE_WORK_ATTENDANCE_POLICY_ACKNOWLEDGEMENT_UPDATE = 'EMPLOYEE_WORK_ATTENDANCE_POLICY_ACKNOWLEDGEMENT:UPDATE',
  EMPLOYEE_WORK_ATTENDANCE_POLICY_ACKNOWLEDGEMENT_DELETE = 'EMPLOYEE_WORK_ATTENDANCE_POLICY_ACKNOWLEDGEMENT:DELETE',
  EMPLOYEE_WORK_ATTENDANCE_POLICY_ACKNOWLEDGEMENT_COUNT = 'EMPLOYEE_WORK_ATTENDANCE_POLICY_ACKNOWLEDGEMENT:COUNT',

  // employee permissions
  EMPLOYEE_CREATE = 'EMPLOYEE:CREATE',
  EMPLOYEE_READ = 'EMPLOYEE:READ',
  EMPLOYEE_UPDATE = 'EMPLOYEE:UPDATE',
  EMPLOYEE_DELETE = 'EMPLOYEE:DELETE',
  EMPLOYEE_COUNT = 'EMPLOYEE:COUNT',

  // company permissions
  COMPANY_CREATE = 'COMPANY:CREATE',
  COMPANY_READ = 'COMPANY:READ',
  COMPANY_UPDATE = 'COMPANY:UPDATE',
  COMPANY_DELETE = 'COMPANY:DELETE',
  COMPANY_COUNT = 'COMPANY:COUNT',

  // company_contact_map permissions
  COMPANY_CONTACT_MAP_CREATE = 'COMPANY_CONTACT_MAP:CREATE',
  COMPANY_CONTACT_MAP_READ = 'COMPANY_CONTACT_MAP:READ',
  COMPANY_CONTACT_MAP_UPDATE = 'COMPANY_CONTACT_MAP:UPDATE',
  COMPANY_CONTACT_MAP_DELETE = 'COMPANY_CONTACT_MAP:DELETE',
  COMPANY_CONTACT_MAP_COUNT = 'COMPANY_CONTACT_MAP:COUNT',

  // company_tag permissions
  COMPANY_TAG_CREATE = 'COMPANY_TAG:CREATE',
  COMPANY_TAG_READ = 'COMPANY_TAG:READ',
  COMPANY_TAG_UPDATE = 'COMPANY_TAG:UPDATE',
  COMPANY_TAG_DELETE = 'COMPANY_TAG:DELETE',
  COMPANY_TAG_COUNT = 'COMPANY_TAG:COUNT',

  // contact_tag permissions
  CONTACT_TAG_CREATE = 'CONTACT_TAG:CREATE',
  CONTACT_TAG_READ = 'CONTACT_TAG:READ',
  CONTACT_TAG_UPDATE = 'CONTACT_TAG:UPDATE',
  CONTACT_TAG_DELETE = 'CONTACT_TAG:DELETE',
  CONTACT_TAG_COUNT = 'CONTACT_TAG:COUNT',

  // contact permissions
  CONTACT_CREATE = 'CONTACT:CREATE',
  CONTACT_READ = 'CONTACT:READ',
  CONTACT_UPDATE = 'CONTACT:UPDATE',
  CONTACT_DELETE = 'CONTACT:DELETE',
  CONTACT_COUNT = 'CONTACT:COUNT',

  // crm_bank_info permissions
  CRM_BANK_INFO_CREATE = 'CRM_BANK_INFO:CREATE',
  CRM_BANK_INFO_READ = 'CRM_BANK_INFO:READ',
  CRM_BANK_INFO_UPDATE = 'CRM_BANK_INFO:UPDATE',
  CRM_BANK_INFO_DELETE = 'CRM_BANK_INFO:DELETE',
  CRM_BANK_INFO_COUNT = 'CRM_BANK_INFO:COUNT',

  // crm_document permissions
  CRM_DOCUMENT_CREATE = 'CRM_DOCUMENT:CREATE',
  CRM_DOCUMENT_READ = 'CRM_DOCUMENT:READ',
  CRM_DOCUMENT_UPDATE = 'CRM_DOCUMENT:UPDATE',
  CRM_DOCUMENT_DELETE = 'CRM_DOCUMENT:DELETE',
  CRM_DOCUMENT_COUNT = 'CRM_DOCUMENT:COUNT',

  // crm_message permissions
  CRM_MESSAGE_CREATE = 'CRM_MESSAGE:CREATE',
  CRM_MESSAGE_READ = 'CRM_MESSAGE:READ',
  CRM_MESSAGE_UPDATE = 'CRM_MESSAGE:UPDATE',
  CRM_MESSAGE_DELETE = 'CRM_MESSAGE:DELETE',
  CRM_MESSAGE_COUNT = 'CRM_MESSAGE:COUNT',

  // crm_note permissions
  CRM_NOTE_CREATE = 'CRM_NOTE:CREATE',
  CRM_NOTE_READ = 'CRM_NOTE:READ',
  CRM_NOTE_UPDATE = 'CRM_NOTE:UPDATE',
  CRM_NOTE_DELETE = 'CRM_NOTE:DELETE',
  CRM_NOTE_COUNT = 'CRM_NOTE:COUNT',

  // crm_referral permissions
  CRM_REFERRAL_CREATE = 'CRM_REFERRAL:CREATE',
  CRM_REFERRAL_READ = 'CRM_REFERRAL:READ',
  CRM_REFERRAL_UPDATE = 'CRM_REFERRAL:UPDATE',
  CRM_REFERRAL_DELETE = 'CRM_REFERRAL:DELETE',
  CRM_REFERRAL_COUNT = 'CRM_REFERRAL:COUNT',

  // crm_team permissions
  CRM_TEAM_CREATE = 'CRM_TEAM:CREATE',
  CRM_TEAM_READ = 'CRM_TEAM:READ',
  CRM_TEAM_UPDATE = 'CRM_TEAM:UPDATE',
  CRM_TEAM_DELETE = 'CRM_TEAM:DELETE',
  CRM_TEAM_COUNT = 'CRM_TEAM:COUNT',

  // group_member permissions
  GROUP_MEMBER_CREATE = 'GROUP_MEMBER:CREATE',
  GROUP_MEMBER_READ = 'GROUP_MEMBER:READ',
  GROUP_MEMBER_UPDATE = 'GROUP_MEMBER:UPDATE',
  GROUP_MEMBER_DELETE = 'GROUP_MEMBER:DELETE',
  GROUP_MEMBER_COUNT = 'GROUP_MEMBER:COUNT',

  // group_message permissions
  GROUP_MESSAGE_CREATE = 'GROUP_MESSAGE:CREATE',
  GROUP_MESSAGE_READ = 'GROUP_MESSAGE:READ',
  GROUP_MESSAGE_UPDATE = 'GROUP_MESSAGE:UPDATE',
  GROUP_MESSAGE_DELETE = 'GROUP_MESSAGE:DELETE',
  GROUP_MESSAGE_COUNT = 'GROUP_MESSAGE:COUNT',

  // group permissions
  GROUP_CREATE = 'GROUP:CREATE',
  GROUP_READ = 'GROUP:READ',
  GROUP_UPDATE = 'GROUP:UPDATE',
  GROUP_DELETE = 'GROUP:DELETE',
  GROUP_COUNT = 'GROUP:COUNT',
  // campaign_prospect permissions
  CAMPAIGN_PROSPECT_CREATE = 'CAMPAIGN_PROSPECT:CREATE',
  CAMPAIGN_PROSPECT_READ = 'CAMPAIGN_PROSPECT:READ',
  CAMPAIGN_PROSPECT_UPDATE = 'CAMPAIGN_PROSPECT:UPDATE',
  CAMPAIGN_PROSPECT_DELETE = 'CAMPAIGN_PROSPECT:DELETE',
  CAMPAIGN_PROSPECT_COUNT = 'CAMPAIGN_PROSPECT:COUNT',

  // campaign_team permissions
  CAMPAIGN_TEAM_CREATE = 'CAMPAIGN_TEAM:CREATE',
  CAMPAIGN_TEAM_READ = 'CAMPAIGN_TEAM:READ',
  CAMPAIGN_TEAM_UPDATE = 'CAMPAIGN_TEAM:UPDATE',
  CAMPAIGN_TEAM_DELETE = 'CAMPAIGN_TEAM:DELETE',
  CAMPAIGN_TEAM_COUNT = 'CAMPAIGN_TEAM:COUNT',

  // campaign permissions
  CAMPAIGN_CREATE = 'CAMPAIGN:CREATE',
  CAMPAIGN_READ = 'CAMPAIGN:READ',
  CAMPAIGN_UPDATE = 'CAMPAIGN:UPDATE',
  CAMPAIGN_DELETE = 'CAMPAIGN:DELETE',
  CAMPAIGN_COUNT = 'CAMPAIGN:COUNT',

  // data_repo permissions
  DATA_REPO_CREATE = 'DATA_REPO:CREATE',
  DATA_REPO_READ = 'DATA_REPO:READ',
  DATA_REPO_UPDATE = 'DATA_REPO:UPDATE',
  DATA_REPO_DELETE = 'DATA_REPO:DELETE',
  DATA_REPO_COUNT = 'DATA_REPO:COUNT',

  // lead_sales_rep permissions
  LEAD_SALES_REP_CREATE = 'LEAD_SALES_REP:CREATE',
  LEAD_SALES_REP_READ = 'LEAD_SALES_REP:READ',
  LEAD_SALES_REP_UPDATE = 'LEAD_SALES_REP:UPDATE',
  LEAD_SALES_REP_DELETE = 'LEAD_SALES_REP:DELETE',
  LEAD_SALES_REP_COUNT = 'LEAD_SALES_REP:COUNT',

  // lead_task_follow_up permissions
  LEAD_TASK_FOLLOW_UP_CREATE = 'LEAD_TASK_FOLLOW_UP:CREATE',
  LEAD_TASK_FOLLOW_UP_READ = 'LEAD_TASK_FOLLOW_UP:READ',
  LEAD_TASK_FOLLOW_UP_UPDATE = 'LEAD_TASK_FOLLOW_UP:UPDATE',
  LEAD_TASK_FOLLOW_UP_DELETE = 'LEAD_TASK_FOLLOW_UP:DELETE',
  LEAD_TASK_FOLLOW_UP_COUNT = 'LEAD_TASK_FOLLOW_UP:COUNT',

  // sales_lead_contact permissions
  SALES_LEAD_CONTACT_CREATE = 'SALES_LEAD_CONTACT:CREATE',
  SALES_LEAD_CONTACT_READ = 'SALES_LEAD_CONTACT:READ',
  SALES_LEAD_CONTACT_UPDATE = 'SALES_LEAD_CONTACT:UPDATE',
  SALES_LEAD_CONTACT_DELETE = 'SALES_LEAD_CONTACT:DELETE',
  SALES_LEAD_CONTACT_COUNT = 'SALES_LEAD_CONTACT:COUNT',

  // sales_lead_note permissions
  SALES_LEAD_NOTE_CREATE = 'SALES_LEAD_NOTE:CREATE',
  SALES_LEAD_NOTE_READ = 'SALES_LEAD_NOTE:READ',
  SALES_LEAD_NOTE_UPDATE = 'SALES_LEAD_NOTE:UPDATE',
  SALES_LEAD_NOTE_DELETE = 'SALES_LEAD_NOTE:DELETE',
  SALES_LEAD_NOTE_COUNT = 'SALES_LEAD_NOTE:COUNT',

  // sales_lead permissions
  SALES_LEAD_CREATE = 'SALES_LEAD:CREATE',
  SALES_LEAD_READ = 'SALES_LEAD:READ',
  SALES_LEAD_UPDATE = 'SALES_LEAD:UPDATE',
  SALES_LEAD_DELETE = 'SALES_LEAD:DELETE',
  SALES_LEAD_COUNT = 'SALES_LEAD:COUNT',

  // contract_multiple_party_sign permissions
  CONTRACT_MULTIPLE_PARTY_SIGN_CREATE = 'CONTRACT_MULTIPLE_PARTY_SIGN:CREATE',
  CONTRACT_MULTIPLE_PARTY_SIGN_READ = 'CONTRACT_MULTIPLE_PARTY_SIGN:READ',
  CONTRACT_MULTIPLE_PARTY_SIGN_UPDATE = 'CONTRACT_MULTIPLE_PARTY_SIGN:UPDATE',
  CONTRACT_MULTIPLE_PARTY_SIGN_DELETE = 'CONTRACT_MULTIPLE_PARTY_SIGN:DELETE',
  CONTRACT_MULTIPLE_PARTY_SIGN_COUNT = 'CONTRACT_MULTIPLE_PARTY_SIGN:COUNT',

  // contract_task_reminder permissions
  CONTRACT_TASK_REMINDER_CREATE = 'CONTRACT_TASK_REMINDER:CREATE',
  CONTRACT_TASK_REMINDER_READ = 'CONTRACT_TASK_REMINDER:READ',
  CONTRACT_TASK_REMINDER_UPDATE = 'CONTRACT_TASK_REMINDER:UPDATE',
  CONTRACT_TASK_REMINDER_DELETE = 'CONTRACT_TASK_REMINDER:DELETE',
  CONTRACT_TASK_REMINDER_COUNT = 'CONTRACT_TASK_REMINDER:COUNT',

  // contract_term permissions
  CONTRACT_TERM_CREATE = 'CONTRACT_TERM:CREATE',
  CONTRACT_TERM_READ = 'CONTRACT_TERM:READ',
  CONTRACT_TERM_UPDATE = 'CONTRACT_TERM:UPDATE',
  CONTRACT_TERM_DELETE = 'CONTRACT_TERM:DELETE',
  CONTRACT_TERM_COUNT = 'CONTRACT_TERM:COUNT',

  // contract permissions
  CONTRACT_CREATE = 'CONTRACT:CREATE',
  CONTRACT_READ = 'CONTRACT:READ',
  CONTRACT_UPDATE = 'CONTRACT:UPDATE',
  CONTRACT_DELETE = 'CONTRACT:DELETE',
  CONTRACT_COUNT = 'CONTRACT:COUNT',

  // discount_code permissions
  DISCOUNT_CODE_CREATE = 'DISCOUNT_CODE:CREATE',
  DISCOUNT_CODE_READ = 'DISCOUNT_CODE:READ',
  DISCOUNT_CODE_UPDATE = 'DISCOUNT_CODE:UPDATE',
  DISCOUNT_CODE_DELETE = 'DISCOUNT_CODE:DELETE',
  DISCOUNT_CODE_COUNT = 'DISCOUNT_CODE:COUNT',

  // order_detail permissions
  ORDER_DETAIL_CREATE = 'ORDER_DETAIL:CREATE',
  ORDER_DETAIL_READ = 'ORDER_DETAIL:READ',
  ORDER_DETAIL_UPDATE = 'ORDER_DETAIL:UPDATE',
  ORDER_DETAIL_DELETE = 'ORDER_DETAIL:DELETE',
  ORDER_DETAIL_COUNT = 'ORDER_DETAIL:COUNT',

  // order_payment permissions
  ORDER_PAYMENT_CREATE = 'ORDER_PAYMENT:CREATE',
  ORDER_PAYMENT_READ = 'ORDER_PAYMENT:READ',
  ORDER_PAYMENT_UPDATE = 'ORDER_PAYMENT:UPDATE',
  ORDER_PAYMENT_DELETE = 'ORDER_PAYMENT:DELETE',
  ORDER_PAYMENT_COUNT = 'ORDER_PAYMENT:COUNT',

  // order permissions
  ORDER_CREATE = 'ORDER:CREATE',
  ORDER_READ = 'ORDER:READ',
  ORDER_UPDATE = 'ORDER:UPDATE',
  ORDER_DELETE = 'ORDER:DELETE',
  ORDER_COUNT = 'ORDER:COUNT',

  // product_category permissions
  PRODUCT_CATEGORY_CREATE = 'PRODUCT_CATEGORY:CREATE',
  PRODUCT_CATEGORY_READ = 'PRODUCT_CATEGORY:READ',
  PRODUCT_CATEGORY_UPDATE = 'PRODUCT_CATEGORY:UPDATE',
  PRODUCT_CATEGORY_DELETE = 'PRODUCT_CATEGORY:DELETE',
  PRODUCT_CATEGORY_COUNT = 'PRODUCT_CATEGORY:COUNT',

  // product permissions
  PRODUCT_CREATE = 'PRODUCT:CREATE',
  PRODUCT_READ = 'PRODUCT:READ',
  PRODUCT_UPDATE = 'PRODUCT:UPDATE',
  PRODUCT_DELETE = 'PRODUCT:DELETE',
  PRODUCT_COUNT = 'PRODUCT:COUNT',

  // shopping_cart permissions
  SHOPPING_CART_CREATE = 'SHOPPING_CART:CREATE',
  SHOPPING_CART_READ = 'SHOPPING_CART:READ',
  SHOPPING_CART_UPDATE = 'SHOPPING_CART:UPDATE',
  SHOPPING_CART_DELETE = 'SHOPPING_CART:DELETE',
  SHOPPING_CART_COUNT = 'SHOPPING_CART:COUNT',

  // store_product_media permissions
  STORE_PRODUCT_MEDIA_CREATE = 'STORE_PRODUCT_MEDIA:CREATE',
  STORE_PRODUCT_MEDIA_READ = 'STORE_PRODUCT_MEDIA:READ',
  STORE_PRODUCT_MEDIA_UPDATE = 'STORE_PRODUCT_MEDIA:UPDATE',
  STORE_PRODUCT_MEDIA_DELETE = 'STORE_PRODUCT_MEDIA:DELETE',
  STORE_PRODUCT_MEDIA_COUNT = 'STORE_PRODUCT_MEDIA:COUNT',

  // store_product_note permissions
  STORE_PRODUCT_NOTE_CREATE = 'STORE_PRODUCT_NOTE:CREATE',
  STORE_PRODUCT_NOTE_READ = 'STORE_PRODUCT_NOTE:READ',
  STORE_PRODUCT_NOTE_UPDATE = 'STORE_PRODUCT_NOTE:UPDATE',
  STORE_PRODUCT_NOTE_DELETE = 'STORE_PRODUCT_NOTE:DELETE',
  STORE_PRODUCT_NOTE_COUNT = 'STORE_PRODUCT_NOTE:COUNT',

  // store_product_tag permissions
  STORE_PRODUCT_TAG_CREATE = 'STORE_PRODUCT_TAG:CREATE',
  STORE_PRODUCT_TAG_READ = 'STORE_PRODUCT_TAG:READ',
  STORE_PRODUCT_TAG_UPDATE = 'STORE_PRODUCT_TAG:UPDATE',
  STORE_PRODUCT_TAG_DELETE = 'STORE_PRODUCT_TAG:DELETE',
  STORE_PRODUCT_TAG_COUNT = 'STORE_PRODUCT_TAG:COUNT',

  // store_product_team permissions
  STORE_PRODUCT_TEAM_CREATE = 'STORE_PRODUCT_TEAM:CREATE',
  STORE_PRODUCT_TEAM_READ = 'STORE_PRODUCT_TEAM:READ',
  STORE_PRODUCT_TEAM_UPDATE = 'STORE_PRODUCT_TEAM:UPDATE',
  STORE_PRODUCT_TEAM_DELETE = 'STORE_PRODUCT_TEAM:DELETE',
  STORE_PRODUCT_TEAM_COUNT = 'STORE_PRODUCT_TEAM:COUNT',

  // store permissions
  STORE_CREATE = 'STORE:CREATE',
  STORE_READ = 'STORE:READ',
  STORE_UPDATE = 'STORE:UPDATE',
  STORE_DELETE = 'STORE:DELETE',
  STORE_COUNT = 'STORE:COUNT',

  // job_applicant_hiring_board permissions
  JOB_APPLICANT_HIRING_BOARD_CREATE = 'JOB_APPLICANT_HIRING_BOARD:CREATE',
  JOB_APPLICANT_HIRING_BOARD_READ = 'JOB_APPLICANT_HIRING_BOARD:READ',
  JOB_APPLICANT_HIRING_BOARD_UPDATE = 'JOB_APPLICANT_HIRING_BOARD:UPDATE',
  JOB_APPLICANT_HIRING_BOARD_DELETE = 'JOB_APPLICANT_HIRING_BOARD:DELETE',
  JOB_APPLICANT_HIRING_BOARD_COUNT = 'JOB_APPLICANT_HIRING_BOARD:COUNT',

  // job_hiring_team permissions
  JOB_HIRING_TEAM_CREATE = 'JOB_HIRING_TEAM:CREATE',
  JOB_HIRING_TEAM_READ = 'JOB_HIRING_TEAM:READ',
  JOB_HIRING_TEAM_UPDATE = 'JOB_HIRING_TEAM:UPDATE',
  JOB_HIRING_TEAM_DELETE = 'JOB_HIRING_TEAM:DELETE',
  JOB_HIRING_TEAM_COUNT = 'JOB_HIRING_TEAM:COUNT',

  // job_master_category permissions
  JOB_MASTER_CATEGORY_CREATE = 'JOB_MASTER_CATEGORY:CREATE',
  JOB_MASTER_CATEGORY_READ = 'JOB_MASTER_CATEGORY:READ',
  JOB_MASTER_CATEGORY_UPDATE = 'JOB_MASTER_CATEGORY:UPDATE',
  JOB_MASTER_CATEGORY_DELETE = 'JOB_MASTER_CATEGORY:DELETE',
  JOB_MASTER_CATEGORY_COUNT = 'JOB_MASTER_CATEGORY:COUNT',

  // job_tag permissions
  JOB_TAG_CREATE = 'JOB_TAG:CREATE',
  JOB_TAG_READ = 'JOB_TAG:READ',
  JOB_TAG_UPDATE = 'JOB_TAG:UPDATE',
  JOB_TAG_DELETE = 'JOB_TAG:DELETE',
  JOB_TAG_COUNT = 'JOB_TAG:COUNT',

  // job_task_interview permissions
  JOB_TASK_INTERVIEW_CREATE = 'JOB_TASK_INTERVIEW:CREATE',
  JOB_TASK_INTERVIEW_READ = 'JOB_TASK_INTERVIEW:READ',
  JOB_TASK_INTERVIEW_UPDATE = 'JOB_TASK_INTERVIEW:UPDATE',
  JOB_TASK_INTERVIEW_DELETE = 'JOB_TASK_INTERVIEW:DELETE',
  JOB_TASK_INTERVIEW_COUNT = 'JOB_TASK_INTERVIEW:COUNT',

  // job permissions
  JOB_CREATE = 'JOB:CREATE',
  JOB_READ = 'JOB:READ',
  JOB_UPDATE = 'JOB:UPDATE',
  JOB_DELETE = 'JOB:DELETE',
  JOB_COUNT = 'JOB:COUNT',
  // course_assignment permissions
  COURSE_ASSIGNMENT_CREATE = 'COURSE_ASSIGNMENT:CREATE',
  COURSE_ASSIGNMENT_READ = 'COURSE_ASSIGNMENT:READ',
  COURSE_ASSIGNMENT_UPDATE = 'COURSE_ASSIGNMENT:UPDATE',
  COURSE_ASSIGNMENT_DELETE = 'COURSE_ASSIGNMENT:DELETE',
  COURSE_ASSIGNMENT_COUNT = 'COURSE_ASSIGNMENT:COUNT',

  // course_bundle_course permissions
  COURSE_BUNDLE_COURSE_CREATE = 'COURSE_BUNDLE_COURSE:CREATE',
  COURSE_BUNDLE_COURSE_READ = 'COURSE_BUNDLE_COURSE:READ',
  COURSE_BUNDLE_COURSE_UPDATE = 'COURSE_BUNDLE_COURSE:UPDATE',
  COURSE_BUNDLE_COURSE_DELETE = 'COURSE_BUNDLE_COURSE:DELETE',
  COURSE_BUNDLE_COURSE_COUNT = 'COURSE_BUNDLE_COURSE:COUNT',

  // course_category permissions
  COURSE_CATEGORY_CREATE = 'COURSE_CATEGORY:CREATE',
  COURSE_CATEGORY_READ = 'COURSE_CATEGORY:READ',
  COURSE_CATEGORY_UPDATE = 'COURSE_CATEGORY:UPDATE',
  COURSE_CATEGORY_DELETE = 'COURSE_CATEGORY:DELETE',
  COURSE_CATEGORY_COUNT = 'COURSE_CATEGORY:COUNT',

  // course_exam permissions
  COURSE_EXAM_CREATE = 'COURSE_EXAM:CREATE',
  COURSE_EXAM_READ = 'COURSE_EXAM:READ',
  COURSE_EXAM_UPDATE = 'COURSE_EXAM:UPDATE',
  COURSE_EXAM_DELETE = 'COURSE_EXAM:DELETE',
  COURSE_EXAM_COUNT = 'COURSE_EXAM:COUNT',

  // course_lesson_quiz permissions
  COURSE_LESSON_QUIZ_CREATE = 'COURSE_LESSON_QUIZ:CREATE',
  COURSE_LESSON_QUIZ_READ = 'COURSE_LESSON_QUIZ:READ',
  COURSE_LESSON_QUIZ_UPDATE = 'COURSE_LESSON_QUIZ:UPDATE',
  COURSE_LESSON_QUIZ_DELETE = 'COURSE_LESSON_QUIZ:DELETE',
  COURSE_LESSON_QUIZ_COUNT = 'COURSE_LESSON_QUIZ:COUNT',

  // course_lesson permissions
  COURSE_LESSON_CREATE = 'COURSE_LESSON:CREATE',
  COURSE_LESSON_READ = 'COURSE_LESSON:READ',
  COURSE_LESSON_UPDATE = 'COURSE_LESSON:UPDATE',
  COURSE_LESSON_DELETE = 'COURSE_LESSON:DELETE',
  COURSE_LESSON_COUNT = 'COURSE_LESSON:COUNT',

  // course_media permissions
  COURSE_MEDIA_CREATE = 'COURSE_MEDIA:CREATE',
  COURSE_MEDIA_READ = 'COURSE_MEDIA:READ',
  COURSE_MEDIA_UPDATE = 'COURSE_MEDIA:UPDATE',
  COURSE_MEDIA_DELETE = 'COURSE_MEDIA:DELETE',
  COURSE_MEDIA_COUNT = 'COURSE_MEDIA:COUNT',

  // course_module permissions
  COURSE_MODULE_CREATE = 'COURSE_MODULE:CREATE',
  COURSE_MODULE_READ = 'COURSE_MODULE:READ',
  COURSE_MODULE_UPDATE = 'COURSE_MODULE:UPDATE',
  COURSE_MODULE_DELETE = 'COURSE_MODULE:DELETE',
  COURSE_MODULE_COUNT = 'COURSE_MODULE:COUNT',

  // course_multiple_tutor permissions
  COURSE_MULTIPLE_TUTOR_CREATE = 'COURSE_MULTIPLE_TUTOR:CREATE',
  COURSE_MULTIPLE_TUTOR_READ = 'COURSE_MULTIPLE_TUTOR:READ',
  COURSE_MULTIPLE_TUTOR_UPDATE = 'COURSE_MULTIPLE_TUTOR:UPDATE',
  COURSE_MULTIPLE_TUTOR_DELETE = 'COURSE_MULTIPLE_TUTOR:DELETE',
  COURSE_MULTIPLE_TUTOR_COUNT = 'COURSE_MULTIPLE_TUTOR:COUNT',

  // course_schedule permissions
  COURSE_SCHEDULE_CREATE = 'COURSE_SCHEDULE:CREATE',
  COURSE_SCHEDULE_READ = 'COURSE_SCHEDULE:READ',
  COURSE_SCHEDULE_UPDATE = 'COURSE_SCHEDULE:UPDATE',
  COURSE_SCHEDULE_DELETE = 'COURSE_SCHEDULE:DELETE',
  COURSE_SCHEDULE_COUNT = 'COURSE_SCHEDULE:COUNT',

  // course_tag permissions
  COURSE_TAG_CREATE = 'COURSE_TAG:CREATE',
  COURSE_TAG_READ = 'COURSE_TAG:READ',
  COURSE_TAG_UPDATE = 'COURSE_TAG:UPDATE',
  COURSE_TAG_DELETE = 'COURSE_TAG:DELETE',
  COURSE_TAG_COUNT = 'COURSE_TAG:COUNT',

  // course_tutoring_session_count permissions
  COURSE_TUTORING_SESSION_COUNT_CREATE = 'COURSE_TUTORING_SESSION_COUNT:CREATE',
  COURSE_TUTORING_SESSION_COUNT_READ = 'COURSE_TUTORING_SESSION_COUNT:READ',
  COURSE_TUTORING_SESSION_COUNT_UPDATE = 'COURSE_TUTORING_SESSION_COUNT:UPDATE',
  COURSE_TUTORING_SESSION_COUNT_DELETE = 'COURSE_TUTORING_SESSION_COUNT:DELETE',
  COURSE_TUTORING_SESSION_COUNT_COUNT = 'COURSE_TUTORING_SESSION_COUNT:COUNT',

  // course permissions
  COURSE_CREATE = 'COURSE:CREATE',
  COURSE_READ = 'COURSE:READ',
  COURSE_UPDATE = 'COURSE:UPDATE',
  COURSE_DELETE = 'COURSE:DELETE',
  COURSE_COUNT = 'COURSE:COUNT',

  // student_course_assignment_result permissions
  STUDENT_COURSE_ASSIGNMENT_RESULT_CREATE = 'STUDENT_COURSE_ASSIGNMENT_RESULT:CREATE',
  STUDENT_COURSE_ASSIGNMENT_RESULT_READ = 'STUDENT_COURSE_ASSIGNMENT_RESULT:READ',
  STUDENT_COURSE_ASSIGNMENT_RESULT_UPDATE = 'STUDENT_COURSE_ASSIGNMENT_RESULT:UPDATE',
  STUDENT_COURSE_ASSIGNMENT_RESULT_DELETE = 'STUDENT_COURSE_ASSIGNMENT_RESULT:DELETE',
  STUDENT_COURSE_ASSIGNMENT_RESULT_COUNT = 'STUDENT_COURSE_ASSIGNMENT_RESULT:COUNT',

  // student_course_assignment permissions
  STUDENT_COURSE_ASSIGNMENT_CREATE = 'STUDENT_COURSE_ASSIGNMENT:CREATE',
  STUDENT_COURSE_ASSIGNMENT_READ = 'STUDENT_COURSE_ASSIGNMENT:READ',
  STUDENT_COURSE_ASSIGNMENT_UPDATE = 'STUDENT_COURSE_ASSIGNMENT:UPDATE',
  STUDENT_COURSE_ASSIGNMENT_DELETE = 'STUDENT_COURSE_ASSIGNMENT:DELETE',
  STUDENT_COURSE_ASSIGNMENT_COUNT = 'STUDENT_COURSE_ASSIGNMENT:COUNT',

  // student_course_certificate permissions
  STUDENT_COURSE_CERTIFICATE_CREATE = 'STUDENT_COURSE_CERTIFICATE:CREATE',
  STUDENT_COURSE_CERTIFICATE_READ = 'STUDENT_COURSE_CERTIFICATE:READ',
  STUDENT_COURSE_CERTIFICATE_UPDATE = 'STUDENT_COURSE_CERTIFICATE:UPDATE',
  STUDENT_COURSE_CERTIFICATE_DELETE = 'STUDENT_COURSE_CERTIFICATE:DELETE',
  STUDENT_COURSE_CERTIFICATE_COUNT = 'STUDENT_COURSE_CERTIFICATE:COUNT',

  // student_exam_detail_course_recommendation permissions
  STUDENT_EXAM_DETAIL_COURSE_RECOMMENDATION_CREATE = 'STUDENT_EXAM_DETAIL_COURSE_RECOMMENDATION:CREATE',
  STUDENT_EXAM_DETAIL_COURSE_RECOMMENDATION_READ = 'STUDENT_EXAM_DETAIL_COURSE_RECOMMENDATION:READ',
  STUDENT_EXAM_DETAIL_COURSE_RECOMMENDATION_UPDATE = 'STUDENT_EXAM_DETAIL_COURSE_RECOMMENDATION:UPDATE',
  STUDENT_EXAM_DETAIL_COURSE_RECOMMENDATION_DELETE = 'STUDENT_EXAM_DETAIL_COURSE_RECOMMENDATION:DELETE',
  STUDENT_EXAM_DETAIL_COURSE_RECOMMENDATION_COUNT = 'STUDENT_EXAM_DETAIL_COURSE_RECOMMENDATION:COUNT',

  // student_exam_result permissions
  STUDENT_EXAM_RESULT_CREATE = 'STUDENT_EXAM_RESULT:CREATE',
  STUDENT_EXAM_RESULT_READ = 'STUDENT_EXAM_RESULT:READ',
  STUDENT_EXAM_RESULT_UPDATE = 'STUDENT_EXAM_RESULT:UPDATE',
  STUDENT_EXAM_RESULT_DELETE = 'STUDENT_EXAM_RESULT:DELETE',
  STUDENT_EXAM_RESULT_COUNT = 'STUDENT_EXAM_RESULT:COUNT',

  // student_exam permissions
  STUDENT_EXAM_CREATE = 'STUDENT_EXAM:CREATE',
  STUDENT_EXAM_READ = 'STUDENT_EXAM:READ',
  STUDENT_EXAM_UPDATE = 'STUDENT_EXAM:UPDATE',
  STUDENT_EXAM_DELETE = 'STUDENT_EXAM:DELETE',
  STUDENT_EXAM_COUNT = 'STUDENT_EXAM:COUNT',

  // student_guardian_access permission
  STUDENT_GUARDIAN_ACCESS_CREATE = 'STUDENT_GUARDIAN_ACCESS:CREATE',
  STUDENT_GUARDIAN_ACCESS_READ = 'STUDENT_GUARDIAN_ACCESS:READ',
  STUDENT_GUARDIAN_ACCESS_UPDATE = 'STUDENT_GUARDIAN_ACCESS:UPDATE',
  STUDENT_GUARDIAN_ACCESS_DELETE = 'STUDENT_GUARDIAN_ACCESS:DELETE',
  STUDENT_GUARDIAN_ACCESS_COUNT = 'STUDENT_GUARDIAN_ACCESS:COUNT',

  // student_learning_goal permissions
  STUDENT_LEARNING_GOAL_CREATE = 'STUDENT_LEARNING_GOAL:CREATE',
  STUDENT_LEARNING_GOAL_READ = 'STUDENT_LEARNING_GOAL:READ',
  STUDENT_LEARNING_GOAL_UPDATE = 'STUDENT_LEARNING_GOAL:UPDATE',
  STUDENT_LEARNING_GOAL_DELETE = 'STUDENT_LEARNING_GOAL:DELETE',
  STUDENT_LEARNING_GOAL_COUNT = 'STUDENT_LEARNING_GOAL:COUNT',

  // student_learning_schedule_and_tracker permissions
  STUDENT_LEARNING_SCHEDULE_AND_TRACKER_CREATE = 'STUDENT_LEARNING_SCHEDULE_AND_TRACKER:CREATE',
  STUDENT_LEARNING_SCHEDULE_AND_TRACKER_READ = 'STUDENT_LEARNING_SCHEDULE_AND_TRACKER:READ',
  STUDENT_LEARNING_SCHEDULE_AND_TRACKER_UPDATE = 'STUDENT_LEARNING_SCHEDULE_AND_TRACKER:UPDATE',
  STUDENT_LEARNING_SCHEDULE_AND_TRACKER_DELETE = 'STUDENT_LEARNING_SCHEDULE_AND_TRACKER:DELETE',
  STUDENT_LEARNING_SCHEDULE_AND_TRACKER_COUNT = 'STUDENT_LEARNING_SCHEDULE_AND_TRACKER:COUNT',

  // student_quiz_result permissions
  STUDENT_QUIZ_RESULT_CREATE = 'STUDENT_QUIZ_RESULT:CREATE',
  STUDENT_QUIZ_RESULT_READ = 'STUDENT_QUIZ_RESULT:READ',
  STUDENT_QUIZ_RESULT_UPDATE = 'STUDENT_QUIZ_RESULT:UPDATE',
  STUDENT_QUIZ_RESULT_DELETE = 'STUDENT_QUIZ_RESULT:DELETE',
  STUDENT_QUIZ_RESULT_COUNT = 'STUDENT_QUIZ_RESULT:COUNT',

  // student_quiz permissions
  STUDENT_QUIZ_CREATE = 'STUDENT_QUIZ:CREATE',
  STUDENT_QUIZ_READ = 'STUDENT_QUIZ:READ',
  STUDENT_QUIZ_UPDATE = 'STUDENT_QUIZ:UPDATE',
  STUDENT_QUIZ_DELETE = 'STUDENT_QUIZ:DELETE',
  STUDENT_QUIZ_COUNT = 'STUDENT_QUIZ:COUNT',

  // student_tag permissions
  STUDENT_TAG_CREATE = 'STUDENT_TAG:CREATE',
  STUDENT_TAG_READ = 'STUDENT_TAG:READ',
  STUDENT_TAG_UPDATE = 'STUDENT_TAG:UPDATE',
  STUDENT_TAG_DELETE = 'STUDENT_TAG:DELETE',
  STUDENT_TAG_COUNT = 'STUDENT_TAG:COUNT',

  // student_tutoring_entitlement_and_usage permissions
  STUDENT_TUTORING_ENTITLEMENT_AND_USAGE_CREATE = 'STUDENT_TUTORING_ENTITLEMENT_AND_USAGE:CREATE',
  STUDENT_TUTORING_ENTITLEMENT_AND_USAGE_READ = 'STUDENT_TUTORING_ENTITLEMENT_AND_USAGE:READ',
  STUDENT_TUTORING_ENTITLEMENT_AND_USAGE_UPDATE = 'STUDENT_TUTORING_ENTITLEMENT_AND_USAGE:UPDATE',
  STUDENT_TUTORING_ENTITLEMENT_AND_USAGE_DELETE = 'STUDENT_TUTORING_ENTITLEMENT_AND_USAGE:DELETE',
  STUDENT_TUTORING_ENTITLEMENT_AND_USAGE_COUNT = 'STUDENT_TUTORING_ENTITLEMENT_AND_USAGE:COUNT',

  // student_tutoring_rating_by_manager permissions
  STUDENT_TUTORING_RATING_BY_MANAGER_CREATE = 'STUDENT_TUTORING_RATING_BY_MANAGER:CREATE',
  STUDENT_TUTORING_RATING_BY_MANAGER_READ = 'STUDENT_TUTORING_RATING_BY_MANAGER:READ',
  STUDENT_TUTORING_RATING_BY_MANAGER_UPDATE = 'STUDENT_TUTORING_RATING_BY_MANAGER:UPDATE',
  STUDENT_TUTORING_RATING_BY_MANAGER_DELETE = 'STUDENT_TUTORING_RATING_BY_MANAGER:DELETE',
  STUDENT_TUTORING_RATING_BY_MANAGER_COUNT = 'STUDENT_TUTORING_RATING_BY_MANAGER:COUNT',

  // student_tutoring_rating_by_student permissions
  STUDENT_TUTORING_RATING_BY_STUDENT_CREATE = 'STUDENT_TUTORING_RATING_BY_STUDENT:CREATE',
  STUDENT_TUTORING_RATING_BY_STUDENT_READ = 'STUDENT_TUTORING_RATING_BY_STUDENT:READ',
  STUDENT_TUTORING_RATING_BY_STUDENT_UPDATE = 'STUDENT_TUTORING_RATING_BY_STUDENT:UPDATE',
  STUDENT_TUTORING_RATING_BY_STUDENT_DELETE = 'STUDENT_TUTORING_RATING_BY_STUDENT:DELETE',
  STUDENT_TUTORING_RATING_BY_STUDENT_COUNT = 'STUDENT_TUTORING_RATING_BY_STUDENT:COUNT',

  // student_tutoring_rating_by_tutor permissions
  STUDENT_TUTORING_RATING_BY_TUTOR_CREATE = 'STUDENT_TUTORING_RATING_BY_TUTOR:CREATE',
  STUDENT_TUTORING_RATING_BY_TUTOR_READ = 'STUDENT_TUTORING_RATING_BY_TUTOR:READ',
  STUDENT_TUTORING_RATING_BY_TUTOR_UPDATE = 'STUDENT_TUTORING_RATING_BY_TUTOR:UPDATE',
  STUDENT_TUTORING_RATING_BY_TUTOR_DELETE = 'STUDENT_TUTORING_RATING_BY_TUTOR:DELETE',
  STUDENT_TUTORING_RATING_BY_TUTOR_COUNT = 'STUDENT_TUTORING_RATING_BY_TUTOR:COUNT',

  // student_tutoring_session permissions
  STUDENT_TUTORING_SESSION_CREATE = 'STUDENT_TUTORING_SESSION:CREATE',
  STUDENT_TUTORING_SESSION_READ = 'STUDENT_TUTORING_SESSION:READ',
  STUDENT_TUTORING_SESSION_UPDATE = 'STUDENT_TUTORING_SESSION:UPDATE',
  STUDENT_TUTORING_SESSION_DELETE = 'STUDENT_TUTORING_SESSION:DELETE',
  STUDENT_TUTORING_SESSION_COUNT = 'STUDENT_TUTORING_SESSION:COUNT',

  // student permissions
  STUDENT_CREATE = 'STUDENT:CREATE',
  STUDENT_READ = 'STUDENT:READ',
  STUDENT_UPDATE = 'STUDENT:UPDATE',
  STUDENT_DELETE = 'STUDENT:DELETE',
  STUDENT_COUNT = 'STUDENT:COUNT',

  // student_course_enrollment permissions
  STUDENT_COURSE_ENROLLMENT_CREATE = 'STUDENT_COURSE_ENROLLMENT:CREATE',
  STUDENT_COURSE_ENROLLMENT_READ = 'STUDENT_COURSE_ENROLLMENT:READ',
  STUDENT_COURSE_ENROLLMENT_UPDATE = 'STUDENT_COURSE_ENROLLMENT:UPDATE',
  STUDENT_COURSE_ENROLLMENT_DELETE = 'STUDENT_COURSE_ENROLLMENT:DELETE',
  STUDENT_COURSE_ENROLLMENT_COUNT = 'STUDENT_COURSE_ENROLLMENT:COUNT',

  // student_course_recommendation permissions
  STUDENT_COURSE_RECOMMENDATION_CREATE = 'STUDENT_COURSE_RECOMMENDATION:CREATE',
  STUDENT_COURSE_RECOMMENDATION_READ = 'STUDENT_COURSE_RECOMMENDATION:READ',
  STUDENT_COURSE_RECOMMENDATION_UPDATE = 'STUDENT_COURSE_RECOMMENDATION:UPDATE',
  STUDENT_COURSE_RECOMMENDATION_DELETE = 'STUDENT_COURSE_RECOMMENDATION:DELETE',
  STUDENT_COURSE_RECOMMENDATION_COUNT = 'STUDENT_COURSE_RECOMMENDATION:COUNT',

  // tutor_course_expertise permissions
  TUTOR_COURSE_EXPERTISE_CREATE = 'TUTOR_COURSE_EXPERTISE:CREATE',
  TUTOR_COURSE_EXPERTISE_READ = 'TUTOR_COURSE_EXPERTISE:READ',
  TUTOR_COURSE_EXPERTISE_UPDATE = 'TUTOR_COURSE_EXPERTISE:UPDATE',
  TUTOR_COURSE_EXPERTISE_DELETE = 'TUTOR_COURSE_EXPERTISE:DELETE',
  TUTOR_COURSE_EXPERTISE_COUNT = 'TUTOR_COURSE_EXPERTISE:COUNT',

  // tutor_student permissions
  TUTOR_STUDENT_CREATE = 'TUTOR_STUDENT:CREATE',
  TUTOR_STUDENT_READ = 'TUTOR_STUDENT:READ',
  TUTOR_STUDENT_UPDATE = 'TUTOR_STUDENT:UPDATE',
  TUTOR_STUDENT_DELETE = 'TUTOR_STUDENT:DELETE',
  TUTOR_STUDENT_COUNT = 'TUTOR_STUDENT:COUNT',

  // tutor_tag permissions
  TUTOR_TAG_CREATE = 'TUTOR_TAG:CREATE',
  TUTOR_TAG_READ = 'TUTOR_TAG:READ',
  TUTOR_TAG_UPDATE = 'TUTOR_TAG:UPDATE',
  TUTOR_TAG_DELETE = 'TUTOR_TAG:DELETE',
  TUTOR_TAG_COUNT = 'TUTOR_TAG:COUNT',

  // tutor_time_slot permissions
  TUTOR_TIME_SLOT_CREATE = 'TUTOR_TIME_SLOT:CREATE',
  TUTOR_TIME_SLOT_READ = 'TUTOR_TIME_SLOT:READ',
  TUTOR_TIME_SLOT_UPDATE = 'TUTOR_TIME_SLOT:UPDATE',
  TUTOR_TIME_SLOT_DELETE = 'TUTOR_TIME_SLOT:DELETE',
  TUTOR_TIME_SLOT_COUNT = 'TUTOR_TIME_SLOT:COUNT',

  // tutor permissions
  TUTOR_CREATE = 'TUTOR:CREATE',
  TUTOR_READ = 'TUTOR:READ',
  TUTOR_UPDATE = 'TUTOR:UPDATE',
  TUTOR_DELETE = 'TUTOR:DELETE',
  TUTOR_COUNT = 'TUTOR:COUNT',

  // institute_contact_list permissions
  INSTITUTE_CONTACT_LIST_CREATE = 'INSTITUTE_CONTACT_LIST:CREATE',
  INSTITUTE_CONTACT_LIST_READ = 'INSTITUTE_CONTACT_LIST:READ',
  INSTITUTE_CONTACT_LIST_UPDATE = 'INSTITUTE_CONTACT_LIST:UPDATE',
  INSTITUTE_CONTACT_LIST_DELETE = 'INSTITUTE_CONTACT_LIST:DELETE',
  INSTITUTE_CONTACT_LIST_COUNT = 'INSTITUTE_CONTACT_LIST:COUNT',

  // institute_course_list permissions
  INSTITUTE_COURSE_LIST_CREATE = 'INSTITUTE_COURSE_LIST:CREATE',
  INSTITUTE_COURSE_LIST_READ = 'INSTITUTE_COURSE_LIST:READ',
  INSTITUTE_COURSE_LIST_UPDATE = 'INSTITUTE_COURSE_LIST:UPDATE',
  INSTITUTE_COURSE_LIST_DELETE = 'INSTITUTE_COURSE_LIST:DELETE',
  INSTITUTE_COURSE_LIST_COUNT = 'INSTITUTE_COURSE_LIST:COUNT',

  // institute_order_list permissions
  INSTITUTE_ORDER_LIST_CREATE = 'INSTITUTE_ORDER_LIST:CREATE',
  INSTITUTE_ORDER_LIST_READ = 'INSTITUTE_ORDER_LIST:READ',
  INSTITUTE_ORDER_LIST_UPDATE = 'INSTITUTE_ORDER_LIST:UPDATE',
  INSTITUTE_ORDER_LIST_DELETE = 'INSTITUTE_ORDER_LIST:DELETE',
  INSTITUTE_ORDER_LIST_COUNT = 'INSTITUTE_ORDER_LIST:COUNT',

  // institute_scholarship_list permissions
  INSTITUTE_SCHOLARSHIP_LIST_CREATE = 'INSTITUTE_SCHOLARSHIP_LIST:CREATE',
  INSTITUTE_SCHOLARSHIP_LIST_READ = 'INSTITUTE_SCHOLARSHIP_LIST:READ',
  INSTITUTE_SCHOLARSHIP_LIST_UPDATE = 'INSTITUTE_SCHOLARSHIP_LIST:UPDATE',
  INSTITUTE_SCHOLARSHIP_LIST_DELETE = 'INSTITUTE_SCHOLARSHIP_LIST:DELETE',
  INSTITUTE_SCHOLARSHIP_LIST_COUNT = 'INSTITUTE_SCHOLARSHIP_LIST:COUNT',

  // institute_student_list permissions
  INSTITUTE_STUDENT_LIST_CREATE = 'INSTITUTE_STUDENT_LIST:CREATE',
  INSTITUTE_STUDENT_LIST_READ = 'INSTITUTE_STUDENT_LIST:READ',
  INSTITUTE_STUDENT_LIST_UPDATE = 'INSTITUTE_STUDENT_LIST:UPDATE',
  INSTITUTE_STUDENT_LIST_DELETE = 'INSTITUTE_STUDENT_LIST:DELETE',
  INSTITUTE_STUDENT_LIST_COUNT = 'INSTITUTE_STUDENT_LIST:COUNT',

  // institute_tag permissions
  INSTITUTE_TAG_CREATE = 'INSTITUTE_TAG:CREATE',
  INSTITUTE_TAG_READ = 'INSTITUTE_TAG:READ',
  INSTITUTE_TAG_UPDATE = 'INSTITUTE_TAG:UPDATE',
  INSTITUTE_TAG_DELETE = 'INSTITUTE_TAG:DELETE',
  INSTITUTE_TAG_COUNT = 'INSTITUTE_TAG:COUNT',

  // institute_tutor_list permissions
  INSTITUTE_TUTOR_LIST_CREATE = 'INSTITUTE_TUTOR_LIST:CREATE',
  INSTITUTE_TUTOR_LIST_READ = 'INSTITUTE_TUTOR_LIST:READ',
  INSTITUTE_TUTOR_LIST_UPDATE = 'INSTITUTE_TUTOR_LIST:UPDATE',
  INSTITUTE_TUTOR_LIST_DELETE = 'INSTITUTE_TUTOR_LIST:DELETE',
  INSTITUTE_TUTOR_LIST_COUNT = 'INSTITUTE_TUTOR_LIST:COUNT',

  // institute permissions
  INSTITUTE_CREATE = 'INSTITUTE:CREATE',
  INSTITUTE_READ = 'INSTITUTE:READ',
  INSTITUTE_UPDATE = 'INSTITUTE:UPDATE',
  INSTITUTE_DELETE = 'INSTITUTE:DELETE',
  INSTITUTE_COUNT = 'INSTITUTE:COUNT',

  // scholarship_award permissions
  SCHOLARSHIP_AWARD_CREATE = 'SCHOLARSHIP_AWARD:CREATE',
  SCHOLARSHIP_AWARD_READ = 'SCHOLARSHIP_AWARD:READ',
  SCHOLARSHIP_AWARD_UPDATE = 'SCHOLARSHIP_AWARD:UPDATE',
  SCHOLARSHIP_AWARD_DELETE = 'SCHOLARSHIP_AWARD:DELETE',
  SCHOLARSHIP_AWARD_COUNT = 'SCHOLARSHIP_AWARD:COUNT',

  // scholarship_document permissions
  SCHOLARSHIP_DOCUMENT_CREATE = 'SCHOLARSHIP_DOCUMENT:CREATE',
  SCHOLARSHIP_DOCUMENT_READ = 'SCHOLARSHIP_DOCUMENT:READ',
  SCHOLARSHIP_DOCUMENT_UPDATE = 'SCHOLARSHIP_DOCUMENT:UPDATE',
  SCHOLARSHIP_DOCUMENT_DELETE = 'SCHOLARSHIP_DOCUMENT:DELETE',
  SCHOLARSHIP_DOCUMENT_COUNT = 'SCHOLARSHIP_DOCUMENT:COUNT',

  // scholarship_institute_zone_course_map permissions
  SCHOLARSHIP_INSTITUTE_ZONE_COURSE_MAP_CREATE = 'SCHOLARSHIP_INSTITUTE_ZONE_COURSE_MAP:CREATE',
  SCHOLARSHIP_INSTITUTE_ZONE_COURSE_MAP_READ = 'SCHOLARSHIP_INSTITUTE_ZONE_COURSE_MAP:READ',
  SCHOLARSHIP_INSTITUTE_ZONE_COURSE_MAP_UPDATE = 'SCHOLARSHIP_INSTITUTE_ZONE_COURSE_MAP:UPDATE',
  SCHOLARSHIP_INSTITUTE_ZONE_COURSE_MAP_DELETE = 'SCHOLARSHIP_INSTITUTE_ZONE_COURSE_MAP:DELETE',
  SCHOLARSHIP_INSTITUTE_ZONE_COURSE_MAP_COUNT = 'SCHOLARSHIP_INSTITUTE_ZONE_COURSE_MAP:COUNT',

  // scholarship_student_application_document permissions
  SCHOLARSHIP_STUDENT_APPLICATION_DOCUMENT_CREATE = 'SCHOLARSHIP_STUDENT_APPLICATION_DOCUMENT:CREATE',
  SCHOLARSHIP_STUDENT_APPLICATION_DOCUMENT_READ = 'SCHOLARSHIP_STUDENT_APPLICATION_DOCUMENT:READ',
  SCHOLARSHIP_STUDENT_APPLICATION_DOCUMENT_UPDATE = 'SCHOLARSHIP_STUDENT_APPLICATION_DOCUMENT:UPDATE',
  SCHOLARSHIP_STUDENT_APPLICATION_DOCUMENT_DELETE = 'SCHOLARSHIP_STUDENT_APPLICATION_DOCUMENT:DELETE',
  SCHOLARSHIP_STUDENT_APPLICATION_DOCUMENT_COUNT = 'SCHOLARSHIP_STUDENT_APPLICATION_DOCUMENT:COUNT',

  // scholarship_student_application permissions
  SCHOLARSHIP_STUDENT_APPLICATION_CREATE = 'SCHOLARSHIP_STUDENT_APPLICATION:CREATE',
  SCHOLARSHIP_STUDENT_APPLICATION_READ = 'SCHOLARSHIP_STUDENT_APPLICATION:READ',
  SCHOLARSHIP_STUDENT_APPLICATION_UPDATE = 'SCHOLARSHIP_STUDENT_APPLICATION:UPDATE',
  SCHOLARSHIP_STUDENT_APPLICATION_DELETE = 'SCHOLARSHIP_STUDENT_APPLICATION:DELETE',
  SCHOLARSHIP_STUDENT_APPLICATION_COUNT = 'SCHOLARSHIP_STUDENT_APPLICATION:COUNT',

  // scholarship permissions
  SCHOLARSHIP_CREATE = 'SCHOLARSHIP:CREATE',
  SCHOLARSHIP_READ = 'SCHOLARSHIP:READ',
  SCHOLARSHIP_UPDATE = 'SCHOLARSHIP:UPDATE',
  SCHOLARSHIP_DELETE = 'SCHOLARSHIP:DELETE',
  SCHOLARSHIP_COUNT = 'SCHOLARSHIP:COUNT',

  // exam_course_module_lesson_stat permissions
  EXAM_COURSE_MODULE_LESSON_STAT_CREATE = 'EXAM_COURSE_MODULE_LESSON_STAT:CREATE',
  EXAM_COURSE_MODULE_LESSON_STAT_READ = 'EXAM_COURSE_MODULE_LESSON_STAT:READ',
  EXAM_COURSE_MODULE_LESSON_STAT_UPDATE = 'EXAM_COURSE_MODULE_LESSON_STAT:UPDATE',
  EXAM_COURSE_MODULE_LESSON_STAT_DELETE = 'EXAM_COURSE_MODULE_LESSON_STAT:DELETE',
  EXAM_COURSE_MODULE_LESSON_STAT_COUNT = 'EXAM_COURSE_MODULE_LESSON_STAT:COUNT',

  // exam_multiple_author permissions
  EXAM_MULTIPLE_AUTHOR_CREATE = 'EXAM_MULTIPLE_AUTHOR:CREATE',
  EXAM_MULTIPLE_AUTHOR_READ = 'EXAM_MULTIPLE_AUTHOR:READ',
  EXAM_MULTIPLE_AUTHOR_UPDATE = 'EXAM_MULTIPLE_AUTHOR:UPDATE',
  EXAM_MULTIPLE_AUTHOR_DELETE = 'EXAM_MULTIPLE_AUTHOR:DELETE',
  EXAM_MULTIPLE_AUTHOR_COUNT = 'EXAM_MULTIPLE_AUTHOR:COUNT',

  // exam_question_detail permissions
  EXAM_QUESTION_DETAIL_CREATE = 'EXAM_QUESTION_DETAIL:CREATE',
  EXAM_QUESTION_DETAIL_READ = 'EXAM_QUESTION_DETAIL:READ',
  EXAM_QUESTION_DETAIL_UPDATE = 'EXAM_QUESTION_DETAIL:UPDATE',
  EXAM_QUESTION_DETAIL_DELETE = 'EXAM_QUESTION_DETAIL:DELETE',
  EXAM_QUESTION_DETAIL_COUNT = 'EXAM_QUESTION_DETAIL:COUNT',

  // exam_question permissions
  EXAM_QUESTION_CREATE = 'EXAM_QUESTION:CREATE',
  EXAM_QUESTION_READ = 'EXAM_QUESTION:READ',
  EXAM_QUESTION_UPDATE = 'EXAM_QUESTION:UPDATE',
  EXAM_QUESTION_DELETE = 'EXAM_QUESTION:DELETE',
  EXAM_QUESTION_COUNT = 'EXAM_QUESTION:COUNT',

  // exam_schedule permissions
  EXAM_SCHEDULE_CREATE = 'EXAM_SCHEDULE:CREATE',
  EXAM_SCHEDULE_READ = 'EXAM_SCHEDULE:READ',
  EXAM_SCHEDULE_UPDATE = 'EXAM_SCHEDULE:UPDATE',
  EXAM_SCHEDULE_DELETE = 'EXAM_SCHEDULE:DELETE',
  EXAM_SCHEDULE_COUNT = 'EXAM_SCHEDULE:COUNT',

  // exam permissions
  EXAM_CREATE = 'EXAM:CREATE',
  EXAM_READ = 'EXAM:READ',
  EXAM_UPDATE = 'EXAM:UPDATE',
  EXAM_DELETE = 'EXAM:DELETE',
  EXAM_COUNT = 'EXAM:COUNT',
}
